Add safeDeleteMode Configuration
halcyon-tech/vscode-ibmi pull request #1042
Opened 2023-02-03 03:55 UTC by steph-beneschan-256

### Changes

Addressed issue #973 by adding the "safeDeleteMode" configuration. When the user tries to delete a directory:
- If safeDeleteMode is enabled, after the Yes/No prompt the user must type in the name of the directory to confirm its deletion.
- If safeDeleteMode is disabled, the user may delete the directory normally. (By default, this configuration is disabled.)

### Checklist

* [X] have tested my change
* [ ] updated relevant documentation
* [X] Remove any/all `console.log`s I added
* [X] eslint is not complaining
* [X] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [X] **for feature PRs**: PR only includes one feature enhancement.

2023-02-03 04:00 UTC, steph-beneschan-256 commented
I was a bit confused on how to update the documentation, since it seems like the docs are no longer stored in the vscode-ibmi repository. Is there a way that I can update the documentation to reflect the changes?

2023-02-03 07:54 UTC, sebjulliand commented
> I was a bit confused on how to update the documentation, since it seems like the docs are no longer stored in the vscode-ibmi repository. Is there a way that I can update the documentation to reflect the changes?

@steph-beneschan-256 I think you need to make a PR on this repository: https://github.com/halcyon-tech/docs

2023-02-03 15:15 UTC, worksofliam commented
Nice PR. I am going to have a review and test over the weekend! Thank you @steph-beneschan-256!

2023-02-07 19:21 UTC, steph-beneschan-256 commented
> > I was a bit confused on how to update the documentation, since it seems like the docs are no longer stored in the vscode-ibmi repository. Is there a way that I can update the documentation to reflect the changes?
> 
> @steph-beneschan-256 I think you need to make a PR on this repository: https://github.com/halcyon-tech/docs

Thank you Sébastien! I'll take a look

2023-02-11 01:25 UTC, worksofliam commented
@steph-beneschan-256 

Hi!

I just wanted to make you aware that after I have stabilised the release of the debugger I will get around to reviewing this!!

Hang tight and we'll get it in. Thank you!

2023-02-17 08:33 UTC, chrjorgensen commented on src/webviews/login/index.ts
> +    ui.addField(new Field(`paragraph`, `authText`, `Only provide either the password or a private key - fuck, not both.`));
@steph-beneschan-256 Please do mind your language in public code, especially in the UI! 😢

2023-02-17 08:37 UTC, chrjorgensen requested changes
Console.log statements must be removed and UI language must be modified.
This commit seems like an internal one not meant for publishing?

2023-02-17 15:36 UTC, steph-beneschan-256 commented
I am so sorry!!
I was experimenting with new changes yesterday and meant to push them to my fork. I did not know that the new changes would end up in this pull request.

2023-02-18 15:38 UTC, worksofliam requested changes
This is a really nice change, thank you! 

Please see my review and then I shall move onto some user testing.

2023-02-18 15:38 UTC, worksofliam commented on src/views/ifsBrowser.js
> +              const dirName = dirSplit[dirSplit.length - 2];  //Get name of directory
I'm not sure how I feel about this code.

Perhaps it could be converted to use `path.basename(node.path.substring(0, node.path.length-1))`, which then also removes the need for `dirSplit`.

2023-02-19 04:34 UTC, steph-beneschan-256 commented on src/views/ifsBrowser.js
> +              const dirName = dirSplit[dirSplit.length - 2];  //Get name of directory
Thank you for your advice! I have updated the code accordingly.

2023-02-21 00:39 UTC, worksofliam approved these changes
Code looks good, and I've tested it - working like a charm.

Thank you @steph-beneschan-256!!

2023-02-21 00:39 UTC, merged