Default deploy directory on input
halcyon-tech/vscode-ibmi pull request #1112
Opened 2023-03-03 18:38 UTC by worksofliam

### Changes

When calling the command to set the deploy directory without a path, set the default in the user input.

### Checklist

* [ ] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2023-03-11 11:59 UTC, sebjulliand requested changes

2023-03-11 11:59 UTC, sebjulliand commented on src/api/local/deployment.ts
> +    const possibleDeployDir = path.posix.join(`/`, `home`, connection!.currentUser, `builds`, workspaceFolder ? workspaceFolder.name : `codebase`);
How about using the actual and/or configured home directory?
```suggestion
    const possibleDeployDir = path.posix.join(connection?.config?.homeDirectory || `/home`, connection!.currentUser, `builds`, workspaceFolder ? workspaceFolder.name : `codebase`);
```

2023-03-12 14:53 UTC, worksofliam commented on src/api/local/deployment.ts
> +    const possibleDeployDir = path.posix.join(`/`, `home`, connection!.currentUser, `builds`, workspaceFolder ? workspaceFolder.name : `codebase`);
@sebjulliand Yes. The reason we build the path is because `config.homeDirectory` is not actually the home directory all the time. It acts more like the 'working directory', and we don't want to build path to be based on the working directory.

2023-03-13 12:22 UTC, sebjulliand commented on src/api/local/deployment.ts
> +    const possibleDeployDir = path.posix.join(`/`, `home`, connection!.currentUser, `builds`, workspaceFolder ? workspaceFolder.name : `codebase`);
Sounds about right.
Now, call me paranoid, but I'd run `pwd` or `echo ~` and get the output here to get the actual home directory. I know most of the time `/home/<username>` is the actual home dir but...better safe than sorry? 😁

2023-03-19 03:48 UTC, worksofliam commented
Next step for this PR is to determine the best way to get the user's home directory. Converting to draft for now.

2023-05-16 14:12 UTC, closed without merging

2023-05-16 14:12 UTC, worksofliam commented
Looks like Seb actually solved in the tar re-write.