Give user option to set bash as their default shell when connecting.
halcyon-tech/vscode-ibmi pull request #1134
Opened 2023-03-14 03:02 UTC by beckhamrryyaann

### Changes

Adds feature described in #1074.  Give user option to set bash as their default shell. 

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

2023-03-14 03:07 UTC, beckhamrryyaann commented
The initial PR does not attempt to install bash on the users system if not installed.  The code just gracefully continues on with the rest of the connection logic.  Please advise if this is not acceptable behavior.

2023-03-14 21:07 UTC, chrjorgensen requested changes
@beckhamrryyaann Thanks for making this PR - just a few issues as seen above.

2023-03-14 21:07 UTC, chrjorgensen commented on src/api/IBMi.ts
> +              if (userDefaultShell === bashShellPath &&
This should be `userDefaultShell !== bashShellPath` instead of using `===`!
Now it prompts when my shell is bash already... 😉

2023-03-14 21:07 UTC, chrjorgensen commented on src/api/IBMi.ts
> +          try {
You don't consider the connection property called `enableSQL`... your check for bash should only be done if SQL is enabled, since you use SQL to change the shell for the user.

2023-03-14 22:35 UTC, beckhamrryyaann commented
Oh my !  How embarrassing.  I changed it to === during testing so I could
see the message without having to change my default shell over and over on
my system.   I will makes these corrections hopefully tonight and resubmit
the PR.

On Tuesday, March 14, 2023, Christian Jorgensen ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @beckhamrryyaann <https://github.com/beckhamrryyaann> Thanks for making
> this PR - just a few issues as seen above.
> ------------------------------
>
> In src/api/IBMi.ts
> <https://github.com/halcyon-tech/vscode-ibmi/pull/1134#discussion_r1136176687>
> :
>
> > +            });
> +            if (!commandShellResult.stderr) {
> +              let userDefaultShell = commandShellResult.stdout.trim();
> +              if (userDefaultShell === bashShellPath &&
> +                  this.remoteFeatures['bash']) {
> +                vscode.window.showInformationMessage(`IBM recommends using bash as your default shell.`, `Set shell to bash?`, `Read More`,).then(async choice => {
> +                  switch (choice) {
> +                    case `Set shell to bash?`:
> +                      statement = `CALL QSYS2.SET_PASE_SHELL_INFO('*CURRENT', '/QOpenSys/pkgs/bin/bash')`;
> +                      output = await this.sendCommand({
> +                        command: `LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"`,
> +                        stdin: statement
> +                      });
> +
> +                      if (output.stdout) {
> +                        vscode.window.showInformationMessage(`Default shell in now bash!`);
>
> Small typo in text...
> ------------------------------
>
> In src/api/IBMi.ts
> <https://github.com/halcyon-tech/vscode-ibmi/pull/1134#discussion_r1136201724>
> :
>
> > @@ -570,6 +571,45 @@ export default class IBMi {
>              // Oh well!
>              console.log(e);
>            }
> +
> +          // Check users default shell.
> +          // If not bash and bash is installed, give user option to set bash as default shell.
> +          try {
> +            const bashShellPath = '/QOpenSys/pkgs/bin/bash';
> +            const commandShellResult = await this.sendCommand({
> +              command: `echo $SHELL`
> +            });
> +            if (!commandShellResult.stderr) {
> +              let userDefaultShell = commandShellResult.stdout.trim();
> +              if (userDefaultShell === bashShellPath &&
>
> This should be userDefaultShell !== bashShellPath instead of using ===!
> Now it prompts when my shell is bash already... 😉
> ------------------------------
>
> In src/api/IBMi.ts
> <https://github.com/halcyon-tech/vscode-ibmi/pull/1134#discussion_r1136203857>
> :
>
> > @@ -570,6 +571,45 @@ export default class IBMi {
>              // Oh well!
>              console.log(e);
>            }
> +
> +          // Check users default shell.
> +          // If not bash and bash is installed, give user option to set bash as default shell.
> +          try {
>
> You don't consider the connection property called enableSQL... your check
> for bash should only be done if SQL is enabled, since you use SQL to change
> the shell for the user.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/halcyon-tech/vscode-ibmi/pull/1134#pullrequestreview-1340249561>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABOFOHH6Y4KKYUSLRRSUWD3W4DMZ7ANCNFSM6AAAAAAVZ32CFI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-15 02:48 UTC, beckhamrryyaann commented on src/api/IBMi.ts
> +                        vscode.window.showInformationMessage(`Default shell in now bash!`);
Latest commit fixes

2023-03-15 02:48 UTC, beckhamrryyaann commented on src/api/IBMi.ts
> +              if (userDefaultShell === bashShellPath &&
Latest commit fixes.

2023-03-15 02:51 UTC, beckhamrryyaann commented on src/api/IBMi.ts
> +          try {
Latest commit address issue.  First thing the enhancement does is check to make sure bash is installed and also that sql is enabled.  If both are not true, the enhancement code is skipped.  No calls to server are made so should be more efficient.

2023-03-15 06:27 UTC, chrjorgensen commented on src/api/IBMi.ts
> +          try {
It's working now and I'll approve the changes. If you're up to it, you can make a new PR and use the `chsh` (if installed) to change the user shell instead of using SQL - as described in https://ibmi-oss-docs.readthedocs.io/en/latest/user_setup/README.html#step-4-change-your-default-shell-to-bash. That way you're not dependent on whether SQL is enabled or not...

2023-03-15 06:29 UTC, chrjorgensen approved these changes

2023-03-15 06:31 UTC, chrjorgensen commented
@beckhamrryyaann LGTM - approved and will merge. Thanks for contributing!

2023-03-15 06:31 UTC, merged

2023-03-15 12:31 UTC, beckhamrryyaann commented on src/api/IBMi.ts
> +          try {
@chrjorgensen I'm definitely up for it.  How do you feel if I include both methods (sql or chsh) and use which ever one is usable.  I would default to using sql first like I have, but if sql is disabled and chsh is available I could use that as a fall back?  Are you ok with this?

2023-03-15 14:13 UTC, chrjorgensen commented on src/api/IBMi.ts
> +          try {
@beckhamrryyaann I definitely think you should go for `chsh` and drop SQL - then you can ignore the `enableSQL` setting. Youjust have to check for `chsh` instead... 😜 

Please make a new PR - this one has been merged already...

2023-03-15 14:42 UTC, beckhamrryyaann commented on src/api/IBMi.ts
> +          try {
Ok.   That sounds good.  I will try to get that this week.