Adding Graphical Debugging Through ACS #70
halcyon-tech/vscode-ibmi pull request #114
Opened 2021-03-18 18:25 UTC by dariocs

### Changes

I added command Ctrl+D to launch Debug Manager
I added debugPath to configuration for set the path of debug manager 
I added Debug Manager in the object browser view
If you have db2util , I improved object list performance using OBJECT_STATISTICS instad of DSPOBJD 

Please if my english is not correct feel free to edit the documentation.
Thank you

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [x] have added myself to the contributors' list in the README

2021-03-20 09:22 UTC, chrjorgensen commented
Great idea!

Question: Why not include the relevant jar files and a small Java runtime in this extension, so everything is available to the user from beginning? Could be an add-on to this extension, if this extensions must be kept small and simple.

But once again, great idea!

2021-03-20 14:54 UTC, worksofliam commented
Hi @chrjorgensen.

I don't think it's a good idea to ship them with the extension. We need to try and keep the extension as small as possible in size (thus why we webpack).

If anything, we should make it easy for the user to download if they have not got it installed.

2021-03-20 14:54 UTC, worksofliam commented
@dariocs I plan on taking a look at this in the next few days.

Thank you!!

2021-03-22 13:00 UTC, dariocs reviewed
Adding Graphical Debugging

2021-03-26 10:01 UTC, dariocs commented
@worksofliam  Hi Liam, I don't understand if I have to do something ....

2021-03-26 12:49 UTC, worksofliam commented
@dariocs Hey. I just need to find the time to do a review.

You have many changes so I will need to spend some time to test it.

2021-03-26 19:22 UTC, worksofliam commented on package.json
> +								"default": "C:/Debug/",
Default maybe should be blank, since this is a Windows path. We have to support all places that VS Code runs.

2021-03-26 19:22 UTC, worksofliam commented on src/api/Configuration.js
> +    this.debugPath = base.debugPath || `C:/Debug/`;
Again, the path could be blank.

2021-03-26 19:25 UTC, worksofliam commented
@dariocs First off, thank you for this PR! It's super awesome.

While I will let this one slide, I am not too happy that there are too feature changes in a single PR. 

1. Debug launcher
2. Changes to use SQL in object browser

I need to update the checklist to make sure that doesn't happen again.

I need you to update the default path, then I will resume testing.

2021-03-26 19:26 UTC, worksofliam commented on src/views/objectBrowser.js
> +        let cmd = "java -cp " + debugPath.trim() + "jt400.jar;"+ debugPath.trim() +"tes.jar utilities.DebugMgr";
Maybe a check here for `debugPath` to make sure it is not blank (the default.)

2021-04-08 15:36 UTC, dariocs reviewed
@worksofliam  I made some adjustments , tell me if is ok or needs other changes.

2021-04-08 15:40 UTC, dariocs commented on package.json
> +								"default": "C:/Debug/",
Done

2021-04-08 15:41 UTC, dariocs commented on src/api/Configuration.js
> +    this.debugPath = base.debugPath || `C:/Debug/`;
Done

2021-04-08 15:41 UTC, dariocs commented on src/views/objectBrowser.js
> +        let cmd = "java -cp " + debugPath.trim() + "jt400.jar;"+ debugPath.trim() +"tes.jar utilities.DebugMgr";
Done

2021-06-01 02:47 UTC, worksofliam commented on src/api/IBMiContent.js
>      const tempLib = this.ibmi.config.tempLibrary;
There some issues with indentation here. eslint is complaining.

2021-06-01 02:49 UTC, worksofliam requested changes
Please see my notes. Thanks for your work!

2021-06-01 02:49 UTC, worksofliam commented on src/api/IBMiContent.js
>      const tempLib = this.ibmi.config.tempLibrary;
There some issues with indentation here. eslint is complaining.

2021-06-01 02:49 UTC, worksofliam commented on src/api/IBMiContent.js
> +    if (this.ibmi.remoteFeatures.db2util) {
This change really doesn't belong in this PR, as this would be a separate enhancement.

2021-06-01 02:49 UTC, worksofliam commented on src/views/objectBrowser.js
> +        let exec = require("child_process").exec;
Some more indentation issues. eslint still complaining.

2021-12-06 18:44 UTC, closed without merging