Add member text to source member tooltip
halcyon-tech/vscode-ibmi pull request #1141
Opened 2023-03-16 20:16 UTC by chrjorgensen

### Changes

Add member text to tooltip - idea from issue #1140

### Checklist

* [x] have tested my change
* [x] eslint is not complaining
* [x] **for feature PRs**: PR only includes one feature enhancement.

2023-03-16 21:45 UTC, sebjulliand requested changes

2023-03-16 21:45 UTC, sebjulliand commented on src/views/objectBrowser.js
> +    this.tooltip = `${this.resourceUri.path}\n(${member.text})`
```suggestion
    this.tooltip = `${this.resourceUri.path}${member.text ? `\n(${member.text})` : ``}`;
```
I'd suggest to only add the text if it's present 😉

2023-03-16 21:57 UTC, chrjorgensen commented on src/views/objectBrowser.js
> +    this.tooltip = `${this.resourceUri.path}\n(${member.text})`
Agree...

2023-03-19 02:30 UTC, worksofliam commented
LGTM. Thank you @chrjorgensen!!

@sebjulliand I will leave you to merge whenever you feel ready!

2023-03-19 11:43 UTC, sebjulliand approved these changes

2023-03-19 11:44 UTC, merged