Rework setting default shell by using chsh.  Do not rely on SQL.
halcyon-tech/vscode-ibmi pull request #1144
Opened 2023-03-19 01:15 UTC by beckhamrryyaann

### Changes
Based on the request from @chrjorgensen I have reworked the setting of the default shell to use chsh.  SQL is no longer used.  Both chsh and bash have to be installed before code will check for default shell.

Description of change here.

### Checklist

* [ X] have tested my change
* [ ] updated relevant documentation
* [ X] Remove any/all `console.log`s I added
* [ X] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ X] **for feature PRs**: PR only includes one feature enhancement.

2023-03-19 03:47 UTC, worksofliam commented
@beckhamrryyaann Did this conversation happen in a GitHub issue? What was the issue number for that? I am a bit out of the loop!

2023-03-19 03:58 UTC, beckhamrryyaann commented
@worksofliam see link to the conversation.  It was on my previous pull request.   
https://github.com/halcyon-tech/vscode-ibmi/pull/1134#discussion_r1136585794

2023-03-20 10:00 UTC, chrjorgensen requested changes
Nice work, works like a charm! There is only a minor change needed...

2023-03-20 16:08 UTC, beckhamrryyaann commented on src/api/IBMi.ts
> +                    case `Set shell to bash?`:
fixed.

2023-03-20 23:39 UTC, chrjorgensen commented
@beckhamrryyaann LGTM!

@worksofliam Any comments on this?

2023-03-21 00:14 UTC, worksofliam commented
@chrjorgensen Review incoming this week.

2023-03-23 00:13 UTC, worksofliam commented
@beckhamrryyaann I reviewed and I am super happy with this! I really appreciate your PRs!

I just need you to fix the conflict (we had a big PR merged!), then I will retest again, and we should be good to merge it.

Thanks!

2023-03-23 20:05 UTC, beckhamrryyaann commented
@worksofliam I have fixed the conflicts.....ready for review.

2023-03-25 14:40 UTC, chrjorgensen requested changes
Duplicated code...

2023-03-25 14:40 UTC, chrjorgensen commented on src/api/IBMi.ts
> +        // Check users default shell.
This code is a duplicate of the code block right above - please cleanup.

2023-03-26 03:48 UTC, beckhamrryyaann commented on src/api/IBMi.ts
> +        // Check users default shell.
Let’s  try this again.  Duplicate code removed. sorry about that.  Ready for review.

2023-03-27 21:54 UTC, chrjorgensen approved these changes
Looks good to me and works as expected.

2023-03-27 21:55 UTC, merged