Add Quick Connect
halcyon-tech/vscode-ibmi pull request #1150
Opened 2023-03-21 18:58 UTC by chrjorgensen

### Changes

This PR will add a `Quick Connect` setting in the connection configuration to speed up connecting to the system:

![billede](https://user-images.githubusercontent.com/13275072/226710725-77987827-3f5f-48d5-b6ef-02ee6bb191fc.png)

When selected, the following server settings are taken from the previous connection to the system:
- bad data areas
- all remote features
- ASP info
- CCSID
- encoding values for #@$

These values are stored in connection storage on each connection to the system. So if no previous connection has been done, even though the `Quick Connect` is checked, all settings will be retrieved from the server and stored in the connection configuration to be used on the next connection

For more information, see issue #1122.

### Checklist

* [x] have tested my change
* [x] eslint is not complaining
* [x] **for feature PRs**: PR only includes one feature enhancement.

2023-03-23 01:42 UTC, worksofliam commented
@chrjorgensen This is awesome. I personally love that this is an opt in thing. Please fix up the conflicts and then I will retest again.

2023-03-23 20:28 UTC, sebjulliand requested changes
That's an awesome change and should indeed speed up connection times. Great job!

Maybe you can make a change to enhance the UX a bit more. Having to uncheck the property in the settings, connect and check again the property seems a bit cumbersome. How about having a `Connect and reload settings` command that could force the reloading of the settings even if quick connect is on? This could be a right click action in the connection browser.

2023-03-25 14:35 UTC, chrjorgensen commented
@sebjulliand I now added a connection right-click option to connect and reload server settings:

![billede](https://user-images.githubusercontent.com/13275072/227723618-8f5cb344-0fe8-40da-b485-837f9dfa4989.png)

A new command `ConnectToAndReload` has been created, but is not available in the command palette, only on the right-click menu.

I had to add one parameter to the connect functions to specify that server settings should be reloaded, despite quick connect was set for the connection. Could I have done it better in another way?

2023-03-25 15:34 UTC, sebjulliand commented on src/api/Storage.ts
> +const SERVER_SETTINGS_CACHE_KEY = `serverSettingsCache`;
Since your setting's key depends on a name, make this a function and use it later on, so you don't repeat the key contruction code over and over.
```suggestion
const SERVER_SETTINGS_CACHE_KEY = (name : string) => `serverSettingsCache_${name}`;
```

2023-03-25 15:34 UTC, sebjulliand commented on src/api/Storage.ts
> +    return this.get<CachedServerSettings>(SERVER_SETTINGS_CACHE_KEY.concat(`_${name}`));
Continued from suggestion's above:
```suggestion
    return this.get<CachedServerSettings>(SERVER_SETTINGS_CACHE_KEY(name));
```

2023-03-25 15:34 UTC, sebjulliand commented on src/api/Storage.ts
> +    await this.set(SERVER_SETTINGS_CACHE_KEY.concat(`_${name}`), serverSettings);
```suggestion
    await this.set(SERVER_SETTINGS_CACHE_KEY(name), serverSettings);
```

2023-03-25 15:34 UTC, sebjulliand commented on src/api/Storage.ts
> +    await this.set(SERVER_SETTINGS_CACHE_KEY.concat(`_${name}`), undefined);
```suggestion
    await this.set(SERVER_SETTINGS_CACHE_KEY(name)), undefined);
```

2023-03-25 15:36 UTC, sebjulliand approved these changes
It's all good to me; just a suggestion to consider.

2023-03-25 15:36 UTC, sebjulliand commented
> I had to add one parameter to the connect functions to specify that server settings should be reloaded, despite quick connect was set for the connection. Could I have done it better in another way?

No, that's perfect the way you did it @chrjorgensen !

2023-03-25 15:47 UTC, sebjulliand commented
@chrjorgensen, @worksofliam : shouldn't `Quick connect` actually be turned on by default when creating a connection? I'd tend to think so. What do you guys think?

2023-03-25 15:48 UTC, worksofliam commented
@sebjulliand I am guessing this quick connect would only work after the initial connection so we have some system information.

I haven't tested this PR yet

2023-03-25 15:56 UTC, sebjulliand commented
> @sebjulliand I am guessing this quick connect would only work after the initial connection so we have some system information.

If it's on but nothing's been cached yet, it will perform a normal connection to gather and cache the values. That's why I think it doesn't hurt to have it turned `on` by default.

2023-03-25 16:38 UTC, chrjorgensen commented
Yeah, Quick connect will not break if activated on a connection never used before. For each setting it will check if there's a value in the cache from a previous connection and only then use that value. Otherwise it will go to the server as usual.
So having this on by default will not break anything.

I'm undecided whether this setting is best suited as a connection setting or a global setting. Since it won't break anything and servers very, very rarely change settings, this could just as well be a global setting. What do you guys think?

2023-03-25 17:53 UTC, sebjulliand commented
When you put it this way, I think it should even not be an option at all, but just the built-in behavior. I can't think of a scenario where you'd need to reload the cached settings every time. Since we have the command to reload them on demand, there may be no point to have it as an option at all.

2023-03-25 18:50 UTC, worksofliam commented
> When you put it this way, I think it should even not be an option at all, but just the built-in behavior.

I somewhat agree with it. In fact, I was thinking an option like 'always do a full connect' (which means never use our cached settings) in the VS Code settings would work here. If it's false, it will: use the cached settings if they exist, otherwise do full connect and store them. If it's true.. always do a full connect

2023-04-03 23:30 UTC, chrjorgensen commented
@sebjulliand This PR was so far from master that I had to rebase the changes onto master branch and force push.
I also added a check for remote features in the cache, since new features have been and will be added in the future, and then the cache is not valid.

2023-04-04 19:08 UTC, sebjulliand requested changes
Just a small suggestion; I can't wait to merge this PR, it's so convenient!

2023-04-04 19:08 UTC, sebjulliand commented on src/api/IBMi.ts
> +        } else {
Having an empty block may be confusing, don't you think?
```suggestion
        if (!quickConnect || !cachedServerSettings?.badDataAreasChecked) {
```

2023-04-07 22:25 UTC, chrjorgensen commented on src/api/IBMi.ts
> +        } else {
@sebjulliand I think it's in the eyes of the beholder - to me it's more confusing with two NOT's and an OR... and I would prefer to keep the test for Quick Connect the same in all places. But I will add a comment inside the empty block to clarify it's empty on purpose.

2023-04-07 23:05 UTC, chrjorgensen commented
@sebjulliand I clarified the empty code block - and had to do a new rebase and force-push.

I also made the Quick Connect active by default, per our discussion, and clarified how to reload the server settings in the configuration description.

Looking forward to your review! 😃

2023-04-07 23:14 UTC, chrjorgensen commented
@sebjulliand @worksofliam I agree that the Quick Connect option could be removed and just be the built-in behavior, and this could very well be done in the near future. But I'm a careful guy and like the user to have an option to disable this new functionality, if it somehow would create some kind of problem that we have not yet encountered. Running it as an option for a while is more secure and less disturbant for the user.

2023-04-09 08:36 UTC, sebjulliand requested changes
Everything is fine, save for one detail; it's not directly related to your PR, but it's been highlighted by it 😉

In `src/webviews/settings/index.ts`, the target configuration doesn't get loaded and saved in all cases using the `ConnectionConfiguration.load` and `ConnectionConfiguration.update` method. Since `ConnectionConfiguration.load` isn't used to load the configuration, some default values are not applied for undefined settings, like `Quick Connect`. Consequently, when you edit the connection settings for a connection for which `Quick Connect` is undefined, the checkbox is unchecked. But when the settings will be loaded during the connection, it will actually be `true`. So the settings page is not the exact reflect of the actual settings in this case 😉

Using `ConnectionConfiguration`'s `load` and `update` will also simplify the connection settings page code a little bit and remove some redundant code.

2023-04-09 21:52 UTC, chrjorgensen commented
@sebjulliand I see the problem and is on it...

2023-04-11 14:27 UTC, chrjorgensen commented
@sebjulliand The initialization problem in settings view is now fixed - please test thoroughly, since this is not a trivial code rewrite.

2023-04-11 14:48 UTC, worksofliam commented
@chrjorgensen I had a quick review and I think the whole idea of restarting can be removed now - you're right. I would need to confirm this for `enableSQL` as we use that in a lot of places!

2023-04-11 15:17 UTC, sebjulliand commented on src/webviews/settings/index.ts
> +          await ConnectionConfiguration.update(config);
We should use `instance.setConfig` here. It will call `ConnectionConfiguration.update` and also update the current connection's config if applicable. Otherwise, `instance.getConfig` will return a stale config.
```suggestion
          await instance.setConfig(config);
```

2023-04-11 16:27 UTC, chrjorgensen commented
@sebjulliand Suggestion has been accepted! 😉

2023-04-11 16:37 UTC, sebjulliand approved these changes
I'm all for it!

2023-04-11 17:41 UTC, worksofliam commented on src/api/Configuration.ts
> +      quickConnect: (parameters.quickConnect === true || parameters.quickConnect === undefined)
I tested this and it shows that Quick Connect will be on by default.

2023-04-11 17:47 UTC, worksofliam requested changes
Wrong button

2023-04-11 18:48 UTC, chrjorgensen commented
> Code looks good, but the 'Connect and Reload' right click option doesn't work as expected. Seems like the UI isn't updating after the connection is made?
> 
> Video uploading here: https://youtu.be/wntqwrjuFdM

@worksofliam I see that - looking into it...

2023-04-11 19:32 UTC, chrjorgensen commented
@worksofliam I'm glad I asked you to have a look and do some testing! 😃 There were a problem with two optional parameters to `connect`, one of which were created in master branch after the other were created in my PR branch - and since they were both boolean and optional, no warning were issued during development!

It should have been fixed now, please retest...

2023-04-11 20:56 UTC, worksofliam approved these changes
Yup, looks like it is working as expected now. I really like this feature - thanks for your hard work @chrjorgensen!

I will give you the pleasure of merging.

2023-04-11 21:53 UTC, chrjorgensen commented
> I will give you the pleasure of merging.

Thanks @worksofliam and @sebjulliand

2023-04-11 21:54 UTC, merged