Added capability to sort IFS files and Members by name or date
halcyon-tech/vscode-ibmi pull request #1151
Opened 2023-03-21 21:21 UTC by sebjulliand

### Changes
A new submenu has been added to the IFS directories and Physical Source File items in the explorers:
![image](https://user-images.githubusercontent.com/11096890/226743123-d71d147e-016e-4007-bd78-f9eb4e3afafd.png)
![image](https://user-images.githubusercontent.com/11096890/226743472-0406504b-df66-4196-ade5-94847ba048e9.png)

It allows to sort the content of the selected directory/SPF by name or date.

### Checklist

* [x] have tested my change
* [x] eslint is not complaining

2023-03-21 22:02 UTC, chrjorgensen requested changes
@sebjulliand Nice - just gave it a quick spin, and it worked as expected.

Some minor flaws in the design, that I think should be changed / added - or at least discussed:

- In the IFS browser, only directories have the sort menu. I would like it to work on shortcuts as well, since they point to a directory and shows files when opened.
- In the IFS browser, it would be nice to have the sort menu on files as well, so I don't need to scroll up to find the directory and sort.
- In the Object browser, it would be nice to have the sort menu on members as well, like for IFS files.

This is a great step to assist the user in file handling... and you managed to sort members as well...! 😉

2023-03-23 00:19 UTC, worksofliam commented
@sebjulliand Before I do this I think it might be worth fixing the conflicts here. Sorry about that!

2023-03-23 19:09 UTC, sebjulliand commented
All done @chrjorgensen, you can now sort from members, files and shortcuts.

2023-03-25 15:35 UTC, chrjorgensen reviewed
@sebjulliand Code is working just beautifully - only some thoughts about sort on a closed tree view branch: Does it make sense to have the `Sort` menu on a closed branch? It does nothing visually until one opens the branch. Maybe the branch should open if the user selects to sort on the closed branch?

Another thought is about ascending and descending sort. It depends on the situation what the user is interested in: the oldest member / file or the newest member / file. It would be nice to have some kind of selection - or an indicator for the sorting direction, which would switch to the opposite when selected again. E.g. the user selects to sort by date, and the newest are shown first in the list and there is now an `up` arrow in the menu option. Then the user selects it again, and now the oldest are shown first in list and there is now a `down` arrow in the menu option. You know, like in a grid view. Just an idea...

WDYT?

2023-03-25 15:58 UTC, sebjulliand commented
@chrjorgensen yes, that makes perfect sense. I'll see what can be done 😁

2023-03-26 13:14 UTC, sebjulliand commented
@chrjorgensen, reversing the sort order is easy, but displaying a ⬇ or ⬆ in the command name requires to create separate commands and display one or the other depending on the clicked item's context value which will impact every `when` clause using those items in `package.json`. I'm not quite sure I want to go down this path just to display the current sorting order 😅
Can you think of a better place to display the sorting order? (item description, tooltip...)

2023-03-26 14:48 UTC, sebjulliand commented
@chrjorgensen , you're on.
Sorting is now reversed when re-executed and asking to sort on a closed branch will expand the branch.
Let me know what you think 😊

2023-03-26 18:28 UTC, chrjorgensen requested changes
@sebjulliand Code is still working beautiful, and now with sort direction! 👏 

Only thing discovered is the sort of national characters in name order - and a possible solution is suggested.

I would suggest having the sort order and direction in the item description of the parent (source file/directory), maybe like this:

```
SOURCEFILE (name🔼) description of file
SOURCEFILE (name🔽) description of file
SOURCEFILE (date🔼) description of file
SOURCEFILE (date🔽) description of file
```

2023-03-27 07:36 UTC, sebjulliand commented on src/api/IBMiContent.ts
> +      command: `ls -a -p -L ${order === "date" ? "-t" : ""} ${(order === 'date' && ascending) || (order === "name" && ascending === false) ? "-r" : ""} ${Tools.escapePath(remotePath)}`
You raised an excellent point, thanks. I'll leave it up to `localCompare` to sort by name then.

2023-03-27 08:27 UTC, sebjulliand commented
@chrjorgensen there you go:
![image](https://user-images.githubusercontent.com/11096890/227884808-62e55421-2f0c-411a-9ed3-19bdb2152a65.png)

The sorting order will show in the description (only if changed...otherwise it shows on every directory/SPF and the UI gets bloated 😁).

And the file name comparison uses `localCompare` now.
Let me know how it goes!

2023-03-27 11:10 UTC, chrjorgensen reviewed
@sebjulliand Perfect, this is so great! I will leave it up to @worksofliam to approve, think he should have a go as well. 😃 

One question: Why change `instance` into a function? Just curious...

2023-03-27 11:49 UTC, sebjulliand commented
Thanks @chrjorgensen !
> One question: Why change `instance` into a function? Just curious...

That's because `instance` used to be a constant and it is now a variable (since https://github.com/halcyon-tech/vscode-ibmi/pull/1142). And I found out that if we require the `instance` field outside of a function (at least in JavaScript...I didn't have a problem when importing in TypeScript), we sometimes get the un-initialized variable (depending when the script gets loaded). So to avoid this, I put a function here and there to get the "correct" `instance` field. It won't be necessary once everything will be converted to TS though. 😁

> One small issue: Each time I sort on a directory, a counter and the directory name appears in `DEBUG CONSOLE`

This `console.log` has been here since before I made this change:
![image](https://user-images.githubusercontent.com/11096890/227932142-a928f3fc-4668-4cde-9db0-d93f047e0b95.png)
Maybe we can remove it @worksofliam ?

2023-03-31 14:18 UTC, worksofliam commented
@worksofliam Absolutely we can remove it.

2023-03-31 14:30 UTC, sebjulliand commented
Removed! @chrjorgensen feel free to approve and merge whenever you want!

2023-03-31 18:24 UTC, chrjorgensen requested changes
@sebjulliand The code is working fine - except for some new things I noticed:

1. When a source file or directory is closed and I select by name, it sorts in descending order. I would expect it to sort in ascending order first, then descending?
2. I can't create a filter in the Object Browser with this PR! I get the following error when trying: 
![billede](https://user-images.githubusercontent.com/13275072/229199995-0346030c-e689-41e6-b28a-150f96492231.png)

2023-04-04 18:41 UTC, sebjulliand commented
Thanks @chrjorgensen!
Indeed, recent changes broke the action opening the filter editor.
So that's fixed and now sorting by name on a closes node will sort by name by default.

2023-04-06 13:35 UTC, worksofliam commented
@sebjulliand Is this something I can review in place of Christian? Is this really just needed some user testing? That is something I can do :)

2023-04-06 19:16 UTC, sebjulliand commented
@worksofliam sure, it just need a final test round 😀

2023-04-07 21:17 UTC, chrjorgensen requested changes
@sebjulliand Just gave your last update a spin - but the extension wouldn't even start, but gave this error:
![billede](https://user-images.githubusercontent.com/13275072/230680059-a420a827-3fc0-4e79-8994-d0c274700251.png)

See suggested fix...

2023-04-07 21:17 UTC, chrjorgensen commented on src/extension.ts
> +
Aren't a line like the following missing here?

```suggestion
import IFSBrowser from "./views/ifsBrowser.js";
```

2023-04-08 15:59 UTC, sebjulliand commented
Hmmm... I pulled and ran npm i, started it and it didn't crash. I'd expect
ObjectBrowser to crash as well then, since it's still JS. I'll dig deeper 😉

Le ven. 7 avr. 2023, 23:17, Christian Jorgensen ***@***.***>
a écrit :

> ***@***.**** requested changes on this pull request.
>
> @sebjulliand <https://github.com/sebjulliand> Just gave your last update
> a spin - but the extension wouldn't even start, but gave this error:
> [image: billede]
> <https://user-images.githubusercontent.com/13275072/230680059-a420a827-3fc0-4e79-8994-d0c274700251.png>
>
> See suggested fix...
> ------------------------------
>
> In src/extension.ts
> <https://github.com/halcyon-tech/vscode-ibmi/pull/1151#discussion_r1160968760>
> :
>
> > @@ -19,6 +19,8 @@ import { CompileTools } from "./api/CompileTools";
>  import { HelpView } from "./views/helpView";
>  import { ProfilesView } from "./views/ProfilesView";
>  import * as Debug from './api/debug';
> +
>
> Aren't a line like the following missing here?
> ⬇️ Suggested change
>
> -
> +import IFSBrowser from "./views/ifsBrowser.js";
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/halcyon-tech/vscode-ibmi/pull/1151#pullrequestreview-1376590259>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACUVGOVMJEZN5C5GXDIFP7LXAB77BANCNFSM6AAAAAAWDAABUI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-09 08:09 UTC, sebjulliand commented
@chrjorgensen you were right; I guess I wasn't really awake yesterday 😅
Anyway, it's working now!

2023-04-11 21:44 UTC, worksofliam approved these changes
@sebjulliand I tested and I have to say this is really pushing the UX for VS Code - really excellent job! I also secretly really love the use of emoji here! (⬆️ ⬇️)

So, you have my approval. Next steps for this are:

1. Fixing the conflicts and getting it merged.
2. I would really appreciate another PR with tests for your changes to `getFileList` and `getMemberList`

Thanks for everything!

2023-04-12 07:11 UTC, sebjulliand commented
Thanks a lot @worksofliam!
Conflicts have been resolved. I'll let you merge and a test PR will follow shortly 😉

2023-04-13 01:13 UTC, worksofliam commented
The comparison tests (SQL vs no SQL) for `getMemberList` fails, but to be expected as each types returns a unique `changed` property. I am ok with this, but something to keep in mind when writing new tests @sebjulliand.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/3708366/231620094-939e7e8d-6f06-410b-a641-7f1e44971226.png">

2023-04-13 01:14 UTC, worksofliam approved these changes
Retested after the merge commit and I am very happy!

Time to release 1.8.0!

2023-04-13 01:14 UTC, merged