Add legacy API commands back
halcyon-tech/vscode-ibmi pull request #1232
Opened 2023-04-11 21:20 UTC by worksofliam

### Changes

In a recent PR (#1158), I added `instance.getConnection().runCommand` and removed `code-for-ibmi.runCommand` from our provided commands. `runCommand` is vital to a couple of other extensions, and removing it without giving time to use the new API will cause extensions (like RPGLE and Db2 for i) will just stop working until they start using the new API.

This PR still releases the new API, will let other extensions continue to work, and give time to those maintainers to upgrade to the export APIs instead.

### Checklist

* [ ] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2023-04-11 21:22 UTC, worksofliam commented
Example of output provided by deprecation notice.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/3708366/231291062-4e0f199a-3143-47dd-bf3d-2d39dec467e2.png">

2023-04-12 07:19 UTC, sebjulliand requested changes
That's great! This is a safe way to eventually remove those commands. I just spotted a few typos in the deprecation warnings.
Love the tests BTW!

2023-04-12 07:19 UTC, sebjulliand commented on src/instantiate.ts
> +      console.log(`Command 'code-for-ibmi.runCommand' has been deprecated. There is no guarantee it will be available after 1.8.0. Use 'instance.getContent().runSQL' in the export API.`);
```suggestion
      console.log(`Command 'code-for-ibmi.runQuery' has been deprecated. There is no guarantee it will be available after 1.8.0. Use 'instance.getContent().runSQL' in the export API.`);
```

2023-04-12 07:19 UTC, sebjulliand commented on src/instantiate.ts
> +      console.log(`Command 'code-for-ibmi.runCommand' has been deprecated. There is no guarantee it will be available after 1.8.0. Use 'exports.customUI' in the export API.`);
```suggestion
      console.log(`Command 'code-for-ibmi.launchUI' has been deprecated. There is no guarantee it will be available after 1.8.0. Use 'exports.customUI' in the export API.`);
```

2023-04-12 13:39 UTC, worksofliam commented
@sebjulliand committed your suggestions - please review again

2023-04-12 13:42 UTC, sebjulliand approved these changes
LGTM!

2023-04-12 13:42 UTC, merged