Feature/run cl command
halcyon-tech/vscode-ibmi pull request #1275
Opened 2023-05-07 19:24 UTC by worksofliam

### Changes

Adds ability to run CL commands from the active editor. The reason behind this PR is to make it easier to create and maintain objects from local sources, removing the need to compile as a CL program. It also allows access to standard compile time variables.

Kind of solves the problem in #1269.

* Command/Control + R when connected to either selected command, or if nothing is selected, the command at the cursor.
* Shows message with a button to open the spool file output if it is available.

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/3708366/236698472-3009ba3c-e526-47bd-b16c-bbfffbbc710b.png">

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2023-05-07 19:24 UTC, worksofliam commented
Side question: should this really be part of the CL extension?

2023-05-16 14:56 UTC, chrjorgensen requested changes
@worksofliam Looking good - only a few minor issues...

2023-05-16 14:56 UTC, chrjorgensen commented on src/languages/clle/clRunner.ts
> +        preLine = document.lineAt(line-1).text.trim();
```suggestion
      while ((line-1) >= 0 && preLine.endsWith(`+`)) {
        preLine = document.lineAt(line-1).text.trim();
        line--;
```

...or `line-1` in line 69 will be -1 at the first line in source, and the `lineAt` will fail and the command not extracted...

2023-05-16 14:56 UTC, chrjorgensen commented on src/languages/clle/clRunner.ts
> +                window.showErrorMessage(
```suggestion
                window.showInformationMessage(
```

because I get this:

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/d6c9458c-4b10-43e2-b6e7-e6e6eefa7788)

2023-05-18 21:10 UTC, sebjulliand commented on package.json
> +					"when": "code-for-ibmi:connected"
Only shows in palette if displaying a cl
```suggestion
					"when": "code-for-ibmi:connected && editorLangId === cl"
```

2023-05-18 21:11 UTC, sebjulliand commented on package.json
> +        "mac": "cmd+r",
Keep it aligned 😅
```suggestion
                "key": "ctrl+r",
                "mac": "cmd+r",
```

2023-05-18 21:12 UTC, sebjulliand commented on src/languages/clle/clApi.ts
> +  /** @type {IBMi} */
This should be removed

2023-05-18 21:13 UTC, sebjulliand commented on src/languages/clle/clApi.ts
> +    await connection.remoteCommand(`CRTSRCPF ${tempLib}/QTOOLS`, undefined)
While you're at it, why not use `runCommand`?

2023-05-18 21:13 UTC, sebjulliand commented on src/languages/clle/clApi.ts
> +  await connection.remoteCommand(
Same as above; use `runCommand`?

2023-05-18 21:18 UTC, sebjulliand requested changes
Some minor changes; overall a nice feature that will surely come in handy!
Nice work!

2023-05-20 15:56 UTC, worksofliam commented on src/languages/clle/clApi.ts
> +    await connection.remoteCommand(`CRTSRCPF ${tempLib}/QTOOLS`, undefined)
I will do this in a second PR.

2023-05-20 16:02 UTC, worksofliam commented
The issues have been resolved. Another review whenever you have a moment would be fab. Thanks!

2023-05-23 08:27 UTC, sebjulliand requested changes
A small issue needs to be fixed; otherwise it's brilliant! 😊

2023-05-24 19:46 UTC, sebjulliand approved these changes
Looking good, works as expected! Let's merge!

2023-05-24 19:46 UTC, merged