Fix #1200 show errors on source files with paths lengths over 255 chars
halcyon-tech/vscode-ibmi pull request #1276
Opened 2023-05-09 04:37 UTC by angelorpa

### Changes

Add functions to work with lines of the events file and get the real path of the source file that was compiled taking care of files with paths lengths more than 255 characters to fix #1200 

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

2023-05-16 14:43 UTC, worksofliam requested changes
Works as expected - thanks for a great change.

Before I merge, please see my comment about formatting and then we should be good to go.

Liam

2023-05-16 14:43 UTC, worksofliam commented on src/api/errors/handler.ts
Please run VS Code's formatter on this file.

1. Open the command palette (F1 / Cntrl+Shift+P)
2. Search 'Format Document'

2023-05-17 12:48 UTC, angelorpa commented on src/api/errors/handler.ts
hi @worksofliam I ran the 'Format Document' but nothing change over the file, so i think this is according to the default formatting style.

2023-05-17 13:08 UTC, angelorpa commented on src/api/errors/handler.ts
May be I need to set some config or style rules?, please let me know to take it present for nexts contributions.

2023-05-17 14:34 UTC, angelorpa commented on src/api/errors/handler.ts
#[1d584e6](https://github.com/halcyon-tech/vscode-ibmi/pull/1276/commits/1d584e6555c6424c4c9fb5636c971c2a7fee9ee6)

@worksofliam  I wasn't using the default formatter, i think this is changes that you are specting.  check it and let me know.

2023-05-20 16:04 UTC, worksofliam commented
Functionally works good and looks like the code cleanup is good too!

@chrjorgensen @sebjulliand This is a pretty impact change. Any chance you  two can have a play with compiling code to ensure errors continue to show as they did before?

I plan on writing some tests for this code in another PR.

2023-05-23 07:57 UTC, sebjulliand reviewed
I played around with it and everything worked fine. I compiled from a local project, a remote PF and a remote streamfile (with a long name) and errors were correctly reported.

Great job; code looks good too! 😃

2023-05-26 14:09 UTC, worksofliam commented
@angelorpa Before we can merge this, we need you to pull in the latest changes from `master` and add a test for this change into this file: https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/testing/ileErrors.ts

2023-06-19 20:20 UTC, angelorpa commented
> @angelorpa Before we can merge this, we need you to pull in the latest changes from `master` and add a test for this change into this file: https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/testing/ileErrors.ts

Hi, I did pulled the latest changes and add two cases for handler errors. Please check it, and let me know if something else is needed.

2023-06-22 14:44 UTC, worksofliam approved these changes
Tests are excellent! Thank you! This is a great addition.

2023-06-22 14:44 UTC, merged