Shell checker: Show error and read more button
halcyon-tech/vscode-ibmi pull request #1338
Opened 2023-06-02 03:20 UTC by worksofliam

### Changes

Handles #1337.

* Adds error messages (`stderr`) to shell error modal
* Show 'Read more' button to open docs page with more info regarding this error

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2023-06-02 09:53 UTC, chrjorgensen commented on src/api/IBMi.ts
> +          directory: `/` // Will use root as the working directory for this command
The `directory` has no effect and should be removed - the SSH server is changing directory to the non-existing user home directory before running the command and will return `Could not chdir to home directory /home/xxxxxxx: No such file or directory`

```suggestion
          command: `echo "${checkShellText}"`
        });
        if (checkShellResult.code === 0 && checkShellResult.stdout.split(`\n`)[0] !== checkShellText) {
```

2023-06-02 09:58 UTC, chrjorgensen requested changes
@worksofliam Your change was not enough - the SSH server is the one trying to change to the users home directory at login and setting an error message in `stderr` - and error code 0...!!

I have made a suggestion for a fix, that will work. It basically says to only check the shell output in `stdout` if no errors were found.

2023-06-02 14:46 UTC, worksofliam commented
@chrjorgensen 

Your suggestion is more fitting and I've made a change so the shell check only looks at the the `stdout` (as it should). We already have logic to warn the user if their home directory is bad! 

<img width="600" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/3708366/1ff64668-f8b2-4358-ab10-270840a16c3b">

2023-06-02 17:06 UTC, angelorpa commented
another possibility could be used an SQL query to get user profile info, something like this:

`
SELECT USER_NAME, HOME_DIRECTORY, PASE_SHELL_PATH 
FROM QSYS2.USER_INFO
WHERE USER_NAME = 'USER_NAME'
`

if the HOME_DIRECTORY field is not empty so check the directory path value exist

2023-06-02 17:10 UTC, worksofliam commented
@angelorpa That's a little bit out of context for this PR, but thanks for the idea nonetheless!

2023-06-03 12:03 UTC, chrjorgensen approved these changes
@worksofliam Looking good!

2023-06-03 12:06 UTC, merged