Add schemas back into vsix
halcyon-tech/vscode-ibmi pull request #1383
Opened 2023-06-23 02:20 UTC by worksofliam

### Changes

Looks like the schema defs weren't being put into the vsix because we were just ignoring the entire `src` directory. This will add it back, which will fix the content assist not working for local `iproj.json` and `actions.json` files.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2023-06-24 15:30 UTC, sebjulliand requested changes
The change is good, no questions asked 👍🏻 

However I'd be in favor of moving the `schemas` folder out of `src` (like `snippets`) and move `Objects.ts` and `LocalLanguageActions.ts` elsewhere, each in a different, meaningful location. Thoughts?

2023-06-24 15:31 UTC, worksofliam commented
@sebjulliand great idea. I will move the schema and .ts files before requesting your review again. 

Thanks!

2023-07-04 13:09 UTC, sebjulliand requested changes
Almost OK. You just need to fix the path on line 43 to be `"./schemas/cl.code-snippets"`.

2023-07-04 13:09 UTC, sebjulliand commented on package.json
> +				"url": "./snippets/actions.json"
Wrong location
```suggestion
				"url": "./schemas/actions.json"
```

2023-07-06 18:06 UTC, worksofliam commented
I need to fix the conflict first. Whoops.

2023-07-08 01:25 UTC, worksofliam commented
@sebjulliand Ready for review again. Thanks!

2023-07-08 12:46 UTC, sebjulliand approved these changes
All good now, let's merge!

2023-07-08 12:46 UTC, merged