Add `Create Quick Filter` action
halcyon-tech/vscode-ibmi pull request #1393
Opened 2023-06-26 18:16 UTC by SanjulaGanepola

### Changes

Add `Create Quick Filter` action that allows users to quickly type a filter of the following format: `LIB*` or `LIB/OBJ/MBR.MBRTYPE (OBJTYPE)` where each parameter is optional except the library. For parameters which are not provided, the defaults will be used.

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/32170854/ccd297d8-b58a-4239-bf8f-972a257a5963)

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

2023-06-26 18:18 UTC, SanjulaGanepola commented
@Liam I decided to go with the `symbol-text` icon as it looked like a better fit (let me know if you think `list-filter` might still be better). Also, let me know if you think the regular expression used for parsing can be improved.

2023-06-27 16:09 UTC, worksofliam commented
@SanjulaGanepola We are going to need a matching PR in the docs repo for this functionality too before this can be merged. Thanks!

https://github.com/halcyon-tech/docs/tree/main/docs

2023-06-29 20:14 UTC, SanjulaGanepola commented
Created a PR for the doc updates: https://github.com/halcyon-tech/docs/pull/10

2023-08-15 13:01 UTC, sebjulliand requested changes
Good job, it works as expected. I'd suggest a few changes to make the code flow unambiguous.

I also have two comments:
- Is there an actual need to create a filter to list libraries?
- There is a slight possibility that the new filter has the same name as an existing one. It may be better to name it using `newFilter`'s content and check if this name is already taken (in which case you could append _1 to it).

2023-08-15 18:25 UTC, SanjulaGanepola commented on src/views/objectBrowser.js
> +              }
Since we are using `validateInput` with the regex already, this block should not be reachable so I removed it. Thanks for catching that

2023-08-15 18:26 UTC, SanjulaGanepola commented on src/views/objectBrowser.js
> +          this.refresh();
This is already contained inside of the `if(newFilter)` so I think we know for sure the filter is added.

2023-08-19 08:10 UTC, sebjulliand approved these changes
Changes look good, thanks! On second thought, the possibility that a "Filter 3" already exists when it gets created is so slim we won't worry about it for now.

2023-08-19 08:10 UTC, merged