Read in private key contents on connect
halcyon-tech/vscode-ibmi pull request #1424
Opened 2023-07-08 01:19 UTC by worksofliam

### Changes

Fixes #1422.

Newer versions of node_ssh (and therefore ssh2) require us read the file and pass the buffer.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2023-07-08 19:21 UTC, worksofliam commented
To test this:

1. Use 1.9.4 release to connect with a private key and it should work. 
2. With the master branch, try using the same connection with a private key on master and it should fail.
2. Try using this branch to connect and it should be successful.

2023-07-09 19:18 UTC, chrjorgensen requested changes
@worksofliam I don't get any errors when running master branch and connection using a private key? It works as release 1.9.4?

2023-07-09 19:23 UTC, worksofliam commented
@chrjorgensen can you confirm you also npm installed after switching between branches?

Edmund was getting this issue on master.

2023-07-09 20:40 UTC, worksofliam commented
Ok, looking it further and it seems that ssh2 now only supports these formats: OpenSSH, RFC4716, or PPK format

Edmund, can you `npm i` on master (not this PR) and see if the problem continues? Also ensure your key is one of the above formats.

2023-07-09 21:57 UTC, chrjorgensen commented
@worksofliam Ah, I didn't do `npm i` before testing the master branch - so I've run on the old SSH2 extension. After doing `npm i` it fails as expected. Will test further...

2023-07-09 21:59 UTC, chrjorgensen approved these changes
@worksofliam Your PR works as expected and fixes the private key problem. Good work!

2023-07-09 22:00 UTC, merged