Validate library list when connecting
halcyon-tech/vscode-ibmi pull request #1433
Opened 2023-07-12 14:17 UTC by chrjorgensen

### Changes

This PR was created to partially fix issue #1431 by validating the library list when connecting to a system.
If any libraries in the list does not exist, the user will be prompted to remove them from the list:

![billede](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/c7348581-5f03-4b44-af64-16546f1c194d)

![billede](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/54851165-57a8-4a50-a353-5a93c7aff9ab)

### Checklist

* [x] have tested my change
* [x] eslint is not complaining

2023-07-12 14:42 UTC, chrjorgensen commented
I know this will not fix the issue of operations failing in the extension if a library in the library list is deleted while connected. The configuration can contain many library lists, e.g. (Command) Profiles, that can cause errors in the extension if not valid.

Ideas of whether or how we should handle this are welcome. 😃

2023-07-14 17:58 UTC, worksofliam requested changes
It's working as expected, but I'd like to see a `progress.report` thrown in similar to the other validation operations.

Thanks!

2023-08-14 09:17 UTC, chrjorgensen commented
@worksofliam I added the progress message anyway - please review and approve when convenient. 😃

2023-08-14 15:03 UTC, worksofliam approved these changes
Tested again to be safe and works as expected.

2023-08-14 15:03 UTC, merged