Ability to create home directory
halcyon-tech/vscode-ibmi pull request #1460
Opened 2023-07-30 17:03 UTC by ThePrez

### Changes

Fixes #1205 

Changes:
- Check if home directory exists but is not writeable
- Allow for automatic creation of home directory (after asking the user)
- Added a `console.log` message when creating the home directory (runs counter to PR checklist requirements)
- Remove guidance about giving the user a home directory via `CHGUSRPRF` as I believe it to be incorrect

### Checklist

* [x] have tested my change
* ~~[ ] updated relevant documentation~~ **N/A**
* [ ] Remove any/all `console.log`s I added **(See note above in change list)**
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

2023-07-30 21:28 UTC, chrjorgensen commented
@ThePrez Thanks for the PR, great enhancement of the home directory validation. I will test this asap. :smiley:

2023-07-31 11:01 UTC, chrjorgensen requested changes
@ThePrez Using `~` instead of `$HOME` does not fully work in the default shell `/QOpenSys/usr/bin/bsh`:

```
cd ~
~: No such file or directory
```

We can't assume the users are running `bash` as shell, however much we would like that.
Also, for IBM i users not fully familiar with IFS and shells, I think it's better to have the absolute path from `$HOME` in the IFS browser and not the tilde `~`. And also for us as developers when debugging issues etc.

WDYT?

2023-07-31 11:45 UTC, ThePrez commented
> @ThePrez Using `~` instead of `$HOME` does not fully work in the default shell `/QOpenSys/usr/bin/bsh`:
> 
> ```
> cd ~
> ~: No such file or directory
> ```
> 
> We can't assume the users are running `bash` as shell, however much we would like that.
> Also, for IBM i users not fully familiar with IFS and shells, I think it's better to have the absolute path from `$HOME` in the IFS browser and not the tilde `~`. And also for us as developers when debugging issues etc.
> 
> WDYT?

Thank you. Good catch!
I will revert https://github.com/halcyon-tech/vscode-ibmi/commit/7c43e664af2700dc6c1d079e18be7b5137cef0fc

2023-07-31 22:54 UTC, chrjorgensen commented on src/api/IBMi.ts
> +          let doesHomeExist = (0 === (await this.sendCommand({ command: `test -w $HOME` })).code);
@ThePrez How should the test for write permission to the home directory work? The test is not performed if the `echo` command completes without error - and it never will...

Also, just to check that $HOME points to a directory, maybe your `test` should be changed to `test -d $HOME && test -w $HOME`?

2023-08-01 01:02 UTC, ThePrez commented on src/api/IBMi.ts
> +          let doesHomeExist = (0 === (await this.sendCommand({ command: `test -w $HOME` })).code);
@chrjorgensen, we don't check whether the echo command completes without error, only whether there's something in stdout. Your comment got me rethinking the design, and I'll be pushing up a commit shortly for your opinion. 

Good call on including `test -d`!

2023-08-01 01:11 UTC, ThePrez commented on src/api/IBMi.ts
> +          let doesHomeExist = (0 === (await this.sendCommand({ command: `test -w $HOME` })).code);
Actually I don't think we want the `test -d`. See commit comments

2023-08-01 01:27 UTC, ThePrez commented on src/api/IBMi.ts
> +          let doesHomeExist = (0 === (await this.sendCommand({ command: `test -w $HOME` })).code);
Marking resolved and asking for re-review based on latest commit

2023-08-01 13:22 UTC, chrjorgensen requested changes

2023-08-01 13:22 UTC, chrjorgensen commented on src/api/IBMi.ts
> +            else if (0 !== (await this.sendCommand({ command: `test -w ${actualHomeDir}` })).code) {
@ThePrez I'm sorry, but I still have an issue with the test for writable home directory: My test user has a non-writable home directory, but no error shows up!

The writable test is only done if the `cd` command fails - but `cd` into a non-writable directory does not fail...

Should the test for writable be included in the initial test? Like this:
`echo $HOME && cd && test -w $HOME`

???

This is not as simple as one could expect... 😉

2023-08-01 15:09 UTC, chrjorgensen requested changes

2023-08-08 14:38 UTC, ThePrez commented on src/api/IBMi.ts
> +            else if (0 !== (await this.sendCommand({ command: `test -w ${actualHomeDir}` })).code) {
That makes sense. Does https://github.com/halcyon-tech/vscode-ibmi/pull/1460/commits/287f7c02255dc1327f1414d1689781dc53495518 look right?

2023-08-09 13:25 UTC, chrjorgensen commented on src/api/IBMi.ts
> +            else if (0 !== (await this.sendCommand({ command: `test -w ${actualHomeDir}` })).code) {
Yep, this commit is correct.

2023-08-09 13:29 UTC, chrjorgensen requested changes

2023-08-09 13:29 UTC, chrjorgensen commented on src/api/IBMi.ts
> +            let mkHomeCmd = `mkdir -p ${actualHomeDir} && chown ${connectionObject.username.toLowerCase()} ${actualHomeDir} && chmod 0755 ${actualHomeDir}`;
@ThePrez One issue here: Creation of home directory fails if a previous connection has been made and the home directory set in the configuration.

Maybe the operation should set the working directory to `.` like when you check the directory?

Currently it will run the `mkdir` after changing the directory to the home directory - which does not exists and make the operation fail...

2023-08-09 18:13 UTC, ThePrez commented on src/api/IBMi.ts
> +            let mkHomeCmd = `mkdir -p ${actualHomeDir} && chown ${connectionObject.username.toLowerCase()} ${actualHomeDir} && chmod 0755 ${actualHomeDir}`;
> Maybe the operation should set the working directory to `.` like when you check the directory?
> 
> Currently it will run the `mkdir` after changing the directory to the home directory - which does not exists and make the operation fail...

I don't believe the operation would fail due to the missing home directory. There should be indications in stdout but the exit code should be 0. @chrjorgensen, are you observing that behavior? Based on #1477 I'm guessing so (due to different shell ? permissions?) 

Adding `.` is simple and harmless. Committed at https://github.com/halcyon-tech/vscode-ibmi/pull/1460/commits/7384684c6085a89b1058a7b980a38996de7bab98 . Thanks for thinking through these use cases!

2023-08-09 18:44 UTC, ThePrez commented on src/api/IBMi.ts
> +            let mkHomeCmd = `mkdir -p ${actualHomeDir} && chown ${connectionObject.username.toLowerCase()} ${actualHomeDir} && chmod 0755 ${actualHomeDir}`;
> @ThePrez One issue here: Creation of home directory fails if a previous connection has been made and the home directory set in the configuration. This could happen if the home directory was deleted after previous connection.

This is an interesting use case. A previously-stored home directory might not exist, or the user profile's home directory may have changed.

I think it's debatable what the correct behavior is. Options:
1. Have VSCode respect the prior home directory setting
2. Save the new value and use it in the config accordingly. 

I think option 1 is the obvious choice, and is more diligently respected with commit at d452c5937fb49e7b574b8d3784f8dcc431906294 which cleans up the logic around storing the home directory into the configuration

2023-08-10 07:35 UTC, chrjorgensen commented on src/api/IBMi.ts
> +            let mkHomeCmd = `mkdir -p ${actualHomeDir} && chown ${connectionObject.username.toLowerCase()} ${actualHomeDir} && chmod 0755 ${actualHomeDir}`;
> I don't believe the operation would fail due to the missing home directory.

The `sendCommand` function always sends a directory (either the specified or the config home directory) to the NodeSSH `execCommand`, which then does a `cd` into that directory before running the specified command. If the directory does not exist, the `cd` operation will fail (and the command never executed) and return error code `1` and stderr `______: No such file or directory`.

I got bitten by the same error, as you saw in #1477... 😄 

NodeSSH `execCommand` can have a directory of `null` and will then not change the directory before running the command - but C4i `sendCommand` does not use this feature and will always force a directory change. The only way to avoid this is specifying `.` as the directory for `sendCommand`.

Btw, the stderr `Could not chdir to home directory /home/________: No such file or directory` is from the SSH login - and will be returned for all following commands. @worksofliam Is this something we need to look at?
The initial working directory in such a situation will be the root `/`.

2023-08-10 07:53 UTC, chrjorgensen commented on src/api/IBMi.ts
>              progress.report({message: `Configured home directory reset to ${defaultHomeDir}.`});
I did not see this info message (must have been overwritten by the next progress message) - if you want the user to be notified about this change, maybe it should be written using the `showInformationMessage` function?

2023-08-10 07:54 UTC, chrjorgensen commented on src/api/IBMi.ts
> +            progress.report({message: `Configured home directory reset to ${defaultHomeDir}.`});
I did not see this info message (must have been overwritten by the next progress message) - if you want the user to be notified about this change, maybe it should be written using the `showInformationMessage` function?

2023-08-10 07:55 UTC, chrjorgensen reviewed
@ThePrez Only one question left, then we can approve and merge... 😃

2023-08-10 11:17 UTC, worksofliam commented on src/api/IBMi.ts
> +            let mkHomeCmd = `mkdir -p ${actualHomeDir} && chown ${connectionObject.username.toLowerCase()} ${actualHomeDir} && chmod 0755 ${actualHomeDir}`;
> Could not chdir to home directory /home/________: No such file or directory

I am not sure what we can do in this regard, though correct me if I’m wrong. This message will always appear if the user has a home directory configured on the profile that does not exist.

2023-08-10 11:31 UTC, chrjorgensen commented on src/api/IBMi.ts
> +            let mkHomeCmd = `mkdir -p ${actualHomeDir} && chown ${connectionObject.username.toLowerCase()} ${actualHomeDir} && chmod 0755 ${actualHomeDir}`;
@worksofliam 
> I am not sure what we can do in this regard, though correct me if I’m wrong. This message will always appear if the user has a home directory configured on the profile that does not exist.

I was just surprised that the error message kept appearing in stderr for all commands executed - I would expect it to appear only once. Seems like the stderr is not emptied - an error in NodeSSH?

2023-08-13 21:48 UTC, ThePrez commented on src/api/IBMi.ts
> +            progress.report({message: `Configured home directory reset to ${defaultHomeDir}.`});
Sounds reasonable

2023-08-13 21:48 UTC, ThePrez commented on src/api/IBMi.ts
> +            progress.report({message: `Configured home directory reset to ${defaultHomeDir}.`});
Resolved at https://github.com/halcyon-tech/vscode-ibmi/pull/1460/commits/fe003eb5e075c947500d2dcabbb544309dde22e8

2023-08-14 08:31 UTC, chrjorgensen approved these changes
@ThePrez Perfect - approved and merged.
Welcome aboard, glad to have you as a contributor! 😃

2023-08-14 08:31 UTC, merged