Add warning message if you're *ALLOBJ
halcyon-tech/vscode-ibmi pull request #1479
Opened 2023-08-09 19:02 UTC by ThePrez

### Changes

People shouldn't do development with *ALLOBJ-type authority

### Checklist

* [x] have tested my change
* [x] updated relevant documentation **(n/a)**
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] **for feature PRs**: PR only includes one feature enhancement.

2023-08-10 08:40 UTC, chrjorgensen requested changes
@ThePrez Nice addition - even though I will be met by this message everytime I connect, since I'm the admin... 😆 (but this may make me change my setup and routines 😃)

Could you add a progress message for this and put the code after it? Since this has nothing to do with temp library config...

2023-08-11 13:37 UTC, worksofliam requested changes

2023-08-11 13:37 UTC, worksofliam commented on src/api/IBMi.ts
> +        if (0 == allObjCheckResult.code) {
Please use a strict comparison (`===`)

2023-08-13 21:55 UTC, ThePrez commented on src/api/IBMi.ts
> +        if (0 == allObjCheckResult.code) {
Resolved at https://github.com/halcyon-tech/vscode-ibmi/pull/1479/commits/e6a1a5c74850ed2670a2be7d16656a5776af8772

2023-08-13 21:56 UTC, ThePrez commented
Tweaked surrounding logic at https://github.com/halcyon-tech/vscode-ibmi/pull/1479/commits/e6a1a5c74850ed2670a2be7d16656a5776af8772

2023-08-14 08:56 UTC, chrjorgensen approved these changes
@ThePrez Approved and merged - thanks!

2023-08-14 08:58 UTC, merged