Add support for custom actions
halcyon-tech/vscode-ibmi pull request #1484
Opened 2023-08-11 18:08 UTC by SanjulaGanepola

### Changes

With the removal of `iproj.json` actions in PR #1481, this PR adds the ability to run custom actions with custom deployment method. Also, updates `launchActionSetup` to accept a workspace folder.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

2023-08-14 21:19 UTC, worksofliam commented
@halcyon-tech/core I need some additional eyes on this PR. I am happy with the code and have reviewed with Sanjula, but I'd like a second opinion. I'd also like some additional testing on this for different areas where Actions can be run.

* Running an action from active editors
   * Members
   * IFS
   * Local
* Running actions from views
   * Object Browser
   * IFS Browser

Thank you!

2023-08-15 08:49 UTC, sebjulliand commented on src/instantiate.ts
> +    vscode.commands.registerCommand(`code-for-ibmi.runAction`, async (node: any, group?: any, action?: Action, method?: DeploymentMethod) => {
`group` seems to be unused here.
```suggestion
    vscode.commands.registerCommand(`code-for-ibmi.runAction`, async (node: any, action?: Action, method?: DeploymentMethod) => {
```

2023-08-15 09:13 UTC, sebjulliand commented on src/instantiate.ts
> +            CompileTools.runAction(instance, uri, action, method);
We should `await` here if the caller of the command want to actually wait for it to end.
```suggestion
            await CompileTools.runAction(instance, uri, action, method);
```

2023-08-15 09:14 UTC, sebjulliand requested changes
Code looks good. I just suggested minor changes.

I tested the following cases:
- Run action from current editor (IFS, Member and Local)
- Run action from IFS and Object browsers

Every action ran as expected.

A few other changes to consider though:
- Maybe the `extensions` field in `Action` should be optional now.
- Add a test for the `code-for-ibmi.runAction`, to be on the safe side (with an `Action` defined on the fly).

2023-08-15 12:51 UTC, SanjulaGanepola commented on src/instantiate.ts
> +    vscode.commands.registerCommand(`code-for-ibmi.runAction`, async (node: any, group?: any, action?: Action, method?: DeploymentMethod) => {
Although this parameter is unused, we still need it because when `code-for-ibmi.runAction` is invoked from the editor's context menu, VS Code passes in this parameter (it has to do with the editor tab group).

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/32170854/089cbaa4-e9a1-48ae-995c-13ef005dc682)

2023-08-15 12:52 UTC, SanjulaGanepola commented on src/instantiate.ts
> +            CompileTools.runAction(instance, uri, action, method);
Good point. Update that: cf3a4a5

2023-08-15 13:14 UTC, sebjulliand commented on src/instantiate.ts
> +    vscode.commands.registerCommand(`code-for-ibmi.runAction`, async (node: any, group?: any, action?: Action, method?: DeploymentMethod) => {
Ha right, good catch 😅

2023-08-15 17:34 UTC, SanjulaGanepola commented
I made the following changes to the tests:
- Instead of testing `CompileTools.runAction` directly, I updated the tests to call the `code-for-ibmi.runAction` command as this gives us better coverage
- Added 2 additional tests for custom actions against members and streamfiles

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/32170854/3f6f9f57-ba5a-4f0c-b152-9338bf4108f4)

2023-08-15 17:54 UTC, SanjulaGanepola commented
@sebjulliand As you suggested, I updated the `Actions` interface so that the `extensions` property is now optional -> [98a99f8](https://github.com/halcyon-tech/vscode-ibmi/pull/1484/commits/98a99f8392207e4db03ba0d5066f0ee260d1958c)

However, the actions.json schema was not changed.

2023-08-15 18:36 UTC, worksofliam approved these changes
I have tested the following scenarios:

* Running user defined actions for members
* Running user defined actions for local files
* Test cases are passing

I'd also like an additional approval from someone in @halcyon-tech/core before this gets merged. Thanks!

2023-08-19 08:44 UTC, sebjulliand approved these changes
Looks good and work as expected!

2023-08-21 14:26 UTC, merged