Add search history to member and streamfile searching
halcyon-tech/vscode-ibmi pull request #1532
Opened 2023-09-09 19:25 UTC by chrjorgensen

### Changes

This PR will add a history of search terms, which can be selected from a list when entering a search term in member and streamfiles searches.

![Screenshot from 2023-09-09 21-14-24](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/81e774c5-a8d4-4716-bae7-e46cbdfe35e6)

![Screenshot from 2023-09-09 21-14-52](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/587c7c2a-b824-4329-9049-f9b8ba8c6e5e)

The input dialog has been changed into a quickpick list, where the user can enter a new search term or select one of the previous search terms. The previous search terms are stored in global storage, thus common to all connections.

@sebjulliand Three new messages have been added - can you translate them into French, please?

```
  'ifsBrowser.searchIFS.previousSearches': `Previous search terms`,
  'ifsBrowser.searchIFS.placeholder': `Enter search term or select one of the previous search terms.`,
  'ifsBrowser.searchIFS.placeholder2': `Enter search term.`,
```

### Checklist

* [x] have tested my change
* [x] eslint is not complaining

2023-09-10 16:04 UTC, sebjulliand requested changes
Nice feature @chrjorgensen !
I added (and fixed) the FR translations. I also made a few styling suggestions 😉
Check it out and once you're done we can safely merge this.

2023-09-10 16:04 UTC, sebjulliand commented on src/views/ifsBrowser.js
> +        }
As `searchIFS` always returns an array, you can safely perform the `map` and `sort` operations here all at once and make `result` a `const`.
```suggestion
        const results = (await Search.searchIFS(getInstance(), searchPath, searchTerm))
          .map(a => ({ ...a, label: path.posix.relative(searchPath, a.path) }))
          .sort((a, b) => a.path.localeCompare(b.path));

        if (results.length > 0) {
          results = results;
          setSearchResults(searchTerm, results);
        } else {
          vscode.window.showInformationMessage(t(`ifsBrowser.doSearchInStreamfiles.noResults`, searchTerm, searchPath));
        }
```

2023-09-11 05:55 UTC, chrjorgensen commented on src/views/ifsBrowser.js
> +          let list = [...GlobalStorage.get().getPreviousSearchTerms() || []];
Almost done - the list array is changed later, e.g. when clearing the list, so can't be a `const`...

2023-09-11 05:59 UTC, chrjorgensen commented
@sebjulliand Followed your advices - almost... 😉

2023-09-11 07:44 UTC, sebjulliand commented on src/views/ifsBrowser.js
> +          let list = [...GlobalStorage.get().getPreviousSearchTerms() || []];
Indeed, fair enough 😄

2023-09-11 07:45 UTC, sebjulliand approved these changes
Works fine! Let's merge!

2023-09-11 07:45 UTC, merged