Added functionality to upload and download source members.
halcyon-tech/vscode-ibmi pull request #227
Opened 2021-08-02 13:56 UTC by szsascha

### Changes

Added functionality to upload and download source members. (See issue #46)

It's now possible to up- and download source members by right-clicking the member name in the member browser.

Something to consider: The path routines in code-for-ibmi.uploadAndReplaceMemberAsFile and code-for-ibmi.downloadMemberAsFile are pretty similar to the routines in qsysFs.readFile. Maybe it make more sense to exclude it into an own util class. As far as I can tell, it makes more sense from my point of view to get the qsysFs stuff into the api. 

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in the README
* [x] **for feature PRs**: PR only includes one feature enhancement.

2021-08-03 20:31 UTC, worksofliam commented on src/views/memberBrowser.js
> +            vscode.window.showErrorMessage(`Error reading file! ${e}`);
I wonder if this text could be changed to `Error uploading content to member`?

2021-08-03 20:31 UTC, worksofliam requested changes
Take a look at my commit, then I can get down to testing on my mac and windows systems. Thanks!

2021-08-03 21:07 UTC, szsascha commented on src/views/memberBrowser.js
> +            vscode.window.showErrorMessage(`Error reading file! ${e}`);
Thanks! I've just change the error message you mentioned and in addition the error message for downloading the file.

2021-08-03 21:24 UTC, szsascha reviewed
Added new commit for requested changes.

2021-08-04 19:19 UTC, worksofliam commented
Hey @szsascha I will likely get my review done tonight.

2021-08-11 00:53 UTC, worksofliam approved these changes
Gave it a test and it's working as intended.

2021-08-11 00:53 UTC, worksofliam commented
Thanks for your great work here @szsascha!

2021-08-11 00:53 UTC, merged