Added 2 COBOL compile options
halcyon-tech/vscode-ibmi pull request #258
Opened 2021-08-30 02:51 UTC by adeanbd

Created a compiled COBOL module option
Created a compiled COBOL bundle(Module and Program) option

### Changes

Added 2 compile option for COBOL:
{
            "type": "member",
            "extensions": [
                "CBLLE",
                "CBL"
            ],
            "name": "Create ALL-in-one PGM CBLLE (CRTBNDCBL)",
            "command": "CRTBNDCBL (&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*SOURCE) DBGVIEW(*SOURCE)"
        },
        {
            "type": "member",
            "extensions": [
                "CBLLE",
                "CBL"
            ],
            "name": "Create Module CBLLE (CRTCBLMOD)",
            "command": "CRTCBLMOD MODULE(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*SOURCE) DBGVIEW(*SOURCE)"
        },

### Checklist

* [ ] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in the README
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2021-08-30 03:04 UTC, worksofliam commented
Hey @adeanbd!

Thanks for a great PR! I'll get this reviewed tomorrow and merged.

2021-08-30 23:53 UTC, worksofliam requested changes
I made one note that I need you to change. Should be good other than that!

2021-08-30 23:53 UTC, worksofliam commented on package.json
> +						    "name": "Create ALL-in-one PGM CBLLE (CRTBNDCBL)",
Can this be renamed to `Create Bound COBOL Program`?

2021-08-31 01:46 UTC, adeanbd commented on package.json
> +						    "name": "Create ALL-in-one PGM CBLLE (CRTBNDCBL)",
Hi there,
Yes of course no problem! Sounds more professional ;)

2021-08-31 02:03 UTC, worksofliam commented on package.json
> +						    "name": "Create ALL-in-one PGM CBLLE (CRTBNDCBL)",
@adeanbd Nope! That's it! When you have made the commit to change it I will merge.

2021-09-03 00:07 UTC, worksofliam commented
Hey @adeanbd!

Is it possible for you to make the change requested? I'd like to merge this soon!

Thanks

2021-09-03 23:00 UTC, adeanbd reviewed
OK to change the text to Create Bound COBOL Program (CRTBNDCBL)

2021-09-03 23:06 UTC, adeanbd commented
Hi,
Sorry I'm confuse, and I don't know what to do!
I need to create another Pull request with the changes?
Sorry to slow the process!

2021-09-04 15:24 UTC, worksofliam commented
@adeanbd No problem!

I need you to make a commit to your branch/fork to make the change yourself. I cannot make the change on your fork.

2021-09-08 02:10 UTC, adeanbd commented
@worksofliam Finally!
Free to go!

2021-09-08 02:11 UTC, worksofliam commented
@adeanbd Great work. Thank you!

2021-09-08 02:12 UTC, merged