Save passwords
halcyon-tech/vscode-ibmi pull request #310
Opened 2021-09-21 11:48 UTC by priceaj

### Changes

Implemented secret password storage. 

There is now the option to save a password for a new connection. 

For existing connections one can be set/changed via the new login settings page. 

Deleting a connection will also delete the saved password

Save passwords use the VS Code secrets API and from windows can be seen/removed/amended in "Control Panel > Credential Manager > Windows Credentials"

### Checklist

* [X] have tested my change
* [X] updated relevant documentation
* [X] Remove any/all `console.log`s I added
* [X] eslint is not complaining
* [X] have added myself to the contributors' list in the README
* [X] **for feature PRs**: PR only includes one feature enhancement.

2021-09-21 20:13 UTC, worksofliam commented
About to give this a go now.

2021-09-21 20:17 UTC, worksofliam commented on src/webviews/settings/index.js
>                ...data
Slight issue here.

When the password is passed in, it is being stored in the general connection storage. 

Maybe when calling `store` on line 216, you could also `data.password = undefined`?

2021-09-21 20:18 UTC, worksofliam requested changes
See above comment.

2021-09-21 20:55 UTC, priceaj commented on src/webviews/settings/index.js
>                ...data
ah yes, good spot... the exact opposite of what we are trying to do!

It looks like the new connection function stores explicitly named fields, but this new forms overlays the data object over the existing connection object, which is adding the new field. 

something I need to watch out for I guess!

I'm amending the code to delete the password property out of the data object completely in all cases

2021-09-21 20:56 UTC, priceaj commented
See above comment.

2021-09-22 09:11 UTC, priceaj commented
@worksofliam if you are interested under the hood VS Code use https://github.com/atom/node-keytar to store the secrets.

"On macOS the passwords are managed by the Keychain, on Linux they are managed by the Secret Service API/libsecret, and on Windows they are managed by Credential Vault."

So I think on MacOS you can use this https://support.apple.com/en-gb/guide/keychain-access/kyca1083/mac to view and manage the created password

2021-09-23 01:34 UTC, worksofliam approved these changes
Looking and working great!

2021-09-23 01:34 UTC, merged