Update node-ssh to v12
halcyon-tech/vscode-ibmi pull request #383
Opened 2021-11-08 11:23 UTC by priceaj

### Changes

This PR was in response to an automated vulnerability check from Synk.io

There is a High priority vulnerability in ssh2 v0.8.9: https://snyk.io/test/npm/ssh2/0.8.9

This was resolved in node-ssh v12 by upgrading to node-ssh v1.X but we were still running v11 which used the older version. 

Applied PR and tested that connections etc still worked, everything seems okay on PUB400

### Checklist

* [X] have tested my change
* [X] updated relevant documentation
* [X] Remove any/all `console.log`s I added
* [X] eslint is not complaining
* [X] have added myself to the contributors' list in the README

2021-11-08 13:24 UTC, worksofliam commented
@priceaj Gonna test this later today, then merge and make a release for it.

2021-11-08 21:33 UTC, worksofliam requested changes
Weird. After clearning node_modules and running a fresh `npm i` on your PR, it does not build.

```
barry@barrys-MBP vscode-ibmi % npm i

up to date, audited 318 packages in 542ms

5 vulnerabilities (4 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
barry@barrys-MBP vscode-ibmi % npm run package                                         

> code-for-ibmi@0.7.19 package
> vsce package

Executing prepublish script 'npm run vscode:prepublish'...

> code-for-ibmi@0.7.19 vscode:prepublish
> webpack --mode production

assets by status 694 KiB [cached] 1 asset
modules by path ./node_modules/ 1.28 MiB
  javascript modules 1.2 MiB 96 modules
  ./node_modules/@bendera/vscode-webview-elements/dist/bundled.js 77.3 KiB [built] [code generated]
  ./node_modules/ssh2/package.json 879 bytes [built] [code generated]
modules by path ./src/ 241 KiB
  modules by path ./src/api/*.js 63.9 KiB 9 modules
  modules by path ./src/filesystems/ 17.3 KiB 7 modules
  modules by path ./src/views/*.js 63.1 KiB 6 modules
  modules by path ./src/webviews/ 26.1 KiB 5 modules
  modules by path ./src/languages/ 54.9 KiB 5 modules
  modules by path ./src/*.js 15.8 KiB 2 modules
19 modules

WARNING in ./node_modules/ssh2/lib/protocol/constants.js 7:12-35
Module not found: Error: Can't resolve 'cpu-features' in '/Users/barry/Repos/vscode-ibmi/node_modules/ssh2/lib/protocol'
 @ ./node_modules/ssh2/lib/server.js 26:4-38
 @ ./node_modules/ssh2/lib/index.js 33:10-32
 @ ./node_modules/node-ssh/lib/cjs/index.js 34:31-46
 @ ./src/api/IBMi.js 4:17-36
 @ ./src/Instance.js 4:13-34
 @ ./src/extension.js 8:15-36

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./node_modules/ssh2/lib/protocol/crypto/build/Release/sshcrypto.node 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/ssh2/lib/protocol/crypto.js 30:12-60
 @ ./node_modules/ssh2/lib/server.js 27:29-60
 @ ./node_modules/ssh2/lib/index.js 33:10-32
 @ ./node_modules/node-ssh/lib/cjs/index.js 34:31-46
 @ ./src/api/IBMi.js 4:17-36
 @ ./src/Instance.js 4:13-34
 @ ./src/extension.js 8:15-36

webpack 5.24.3 compiled with 1 error and 1 warning in 3875 ms
 ERROR  npm failed with exit code 1
```

2021-11-08 21:39 UTC, worksofliam commented
@priceaj Looks like ssh2 has brought in a new optional requirement, which is a binary. It says it's optional, so I'd rather not ship it if we'd have to.

https://github.com/mscdex/ssh2#requirements

2021-11-08 22:19 UTC, priceaj commented
Looks like I already have the dependencies required to build cpu-features installed, so it didn't complain on my machine. Could we add the required packages to build as dev dependencies?

2021-11-08 22:21 UTC, worksofliam commented
@priceaj feel free to update the PR to include those deps and I can give it another whirl.

2021-11-08 22:33 UTC, priceaj commented
Looks like it uses node-gyp which actually uses python to build on windows

https://github.com/nodejs/node-gyp/blob/master/README.md

If it's building a binary, wouldn't we need to ship different extensions per platform?

I can't work out if `cpu_features` is optional because ssh2 will build it (i.e it still needs it) or optional because it's not required for functionality

2021-11-09 15:31 UTC, worksofliam commented
This issue is similar to what we're having: https://github.com/mscdex/ssh2/issues/1056

I added this to our webpack config to solve the issue, but then we're shipping a binary, which is something we do not want to do.

```
      {
        test: /\.node$/,
        loader: `node-loader`,
      },
```

2021-11-09 15:53 UTC, worksofliam commented
Okay, I got it to build and run without the native module.

```
// FRESH INSTALL
% npm i
% rm -rf node_modules/ssh2/lib/protocol/crypto/build        
% npm run package                                   

> code-for-ibmi@0.7.19 package
> vsce package

Executing prepublish script 'npm run vscode:prepublish'...

> code-for-ibmi@0.7.19 vscode:prepublish
> webpack --mode production

asset extension.js 694 KiB [emitted] [minimized] (name: main) 2 related assets
modules by path ./node_modules/ 1.14 MiB
  javascript modules 1.06 MiB 95 modules
  ./node_modules/@bendera/vscode-webview-elements/dist/bundled.js 77.3 KiB [built] [code generated]
  ./node_modules/ssh2/package.json 879 bytes [built] [code generated]
modules by path ./src/ 241 KiB
  modules by path ./src/api/*.js 63.9 KiB 9 modules
  modules by path ./src/filesystems/ 17.3 KiB 7 modules
  modules by path ./src/views/*.js 63.1 KiB 6 modules
  modules by path ./src/webviews/ 26.1 KiB 5 modules
  modules by path ./src/languages/ 54.9 KiB 5 modules
  modules by path ./src/*.js 15.8 KiB 2 modules
19 modules

WARNING in ./node_modules/ssh2/lib/protocol/constants.js 7:12-35
Module not found: Error: Can't resolve 'cpu-features' in '/Users/barry/Repos/vscode-ibmi/node_modules/ssh2/lib/protocol'
 @ ./node_modules/ssh2/lib/server.js 26:4-38
 @ ./node_modules/ssh2/lib/index.js 33:10-32
 @ ./node_modules/node-ssh/lib/cjs/index.js 34:31-46
 @ ./src/api/IBMi.js 4:17-36
 @ ./src/Instance.js 4:13-34
 @ ./src/extension.js 8:15-36

WARNING in ./node_modules/ssh2/lib/protocol/crypto.js 30:12-60
Module not found: Error: Can't resolve './crypto/build/Release/sshcrypto.node' in '/Users/barry/Repos/vscode-ibmi/node_modules/ssh2/lib/protocol'
 @ ./node_modules/ssh2/lib/server.js 27:29-60
 @ ./node_modules/ssh2/lib/index.js 33:10-32
 @ ./node_modules/node-ssh/lib/cjs/index.js 34:31-46
 @ ./src/api/IBMi.js 4:17-36
 @ ./src/Instance.js 4:13-34
 @ ./src/extension.js 8:15-36

2 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.24.3 compiled with 2 warnings in 3907 ms
 DONE  Packaged: /Users/barry/Repos/vscode-ibmi/code-for-ibmi-0.7.19.vsix (44 files, 298.51KB)
```

2021-11-09 18:13 UTC, priceaj commented
Was going to look at this tonight. How did you manage to get it to pass the build?

2021-11-09 18:29 UTC, worksofliam commented
@priceaj 

```
rm -rf node_modules/ssh2/lib/protocol/crypto/build
npm run package
```

Remove the optional dep.

2021-11-09 18:31 UTC, priceaj commented
Lol nice hack!

2021-11-10 22:33 UTC, priceaj commented
Do you still need me to make a change to this?

2021-11-10 22:42 UTC, worksofliam commented
Yes if you're able to, but if you want to close it you can - then, whenever I have the time I will pick it up again.

2021-11-10 23:27 UTC, priceaj commented
Give that a go, you will need to clean your node_modules again

2021-11-18 21:21 UTC, priceaj commented
Is this building alright for you? The tag doesn't seem to work if I add it

2021-11-18 21:22 UTC, worksofliam approved these changes

2021-11-18 21:22 UTC, worksofliam commented
@priceaj That is odd.. will need to look into the action some more.

2021-11-18 23:24 UTC, worksofliam commented
@priceaj I think this PR is important so I believe 0.8.3 will be a release which is for this fix.

2021-12-03 12:48 UTC, priceaj commented
wouldn't it have been better to get this in before implementing a new feature which relies on the SSH connection?

2021-12-03 19:04 UTC, worksofliam commented
@priceaj yup. Agreed. This needs to come out sooner than later. 

I'm a bit worried about the hack to get it working so I need to test it some more.

2021-12-03 19:53 UTC, priceaj commented
The only other way I can see is to fork it, but then we will need to maintain it

2021-12-03 20:38 UTC, worksofliam commented
@priceaj Okay. The build is looking good here on Mac.

You're on Windows right? I need you to test the build works on Windows & test the install:

1. Checkout this PR
2. Delete `node_modules`
3. Run `npm i`
4. Run `npm run package`
5. Install the generated vsix
6. Connect to a system and test it's all working as expected

2021-12-03 21:17 UTC, priceaj commented
All looks good on Windows, will try on Ubuntu as well

2021-12-03 21:21 UTC, worksofliam commented
@priceaj I will wait to hear back about Ubuntu.

2021-12-03 21:35 UTC, worksofliam commented
Trying to figure out why the build didn't run.

2021-12-03 23:15 UTC, priceaj commented
Built on Ubuntu and seems to work okay

2021-12-04 01:36 UTC, worksofliam commented
@priceaj thanks for sharing those steps.

I am happy with all this, so I'm going to merge this tonight or tomorrow and get a new release out.

Thanks for your help!

2021-12-04 17:35 UTC, worksofliam commented
@priceaj I tried this branch in a Codespace, since the build is triggering on this PR. I am glad I did, because in the Codespace I am getting this error:

```

> code-for-ibmi@0.8.4 package /workspaces/vscode-ibmi
> vsce package

Executing prepublish script 'npm run vscode:prepublish'...

> code-for-ibmi@0.8.4 vscode:prepublish /workspaces/vscode-ibmi
> rimraf ./node_modules/ssh2/lib/protocol/crypto/build && webpack --mode production

assets by status 682 KiB [cached] 1 asset
modules by path ./node_modules/ 1.2 MiB
  javascript modules 1.13 MiB 97 modules
  ./node_modules/@bendera/vscode-webview-elements/dist/bundled.js 77.3 KiB [built] [code generated]
  ./node_modules/ssh2/package.json 1.57 KiB [built] [code generated]
modules by path ./src/ 214 KiB
  modules by path ./src/api/ 79 KiB 14 modules
  modules by path ./src/filesystems/ 17.3 KiB 7 modules
  modules by path ./src/webviews/ 29.9 KiB 6 modules
  modules by path ./src/views/*.js 56.5 KiB 5 modules
  modules by path ./src/*.js 18.3 KiB 2 modules
  modules by path ./src/languages/clle/*.js 12.9 KiB
    ./src/languages/clle/clCommands.js 11.6 KiB [built] [code generated]
    ./src/languages/clle/gencmdxml.js 1.3 KiB [built] [code generated]
19 modules

WARNING in ./node_modules/ssh2/lib/protocol/crypto.js 30:12-60
Module not found: Error: Can't resolve './crypto/build/Release/sshcrypto.node' in '/workspaces/vscode-ibmi/node_modules/ssh2/lib/protocol'
 @ ./node_modules/ssh2/lib/client.js 34:29-60
 @ ./node_modules/ssh2/lib/index.js 27:10-32
 @ ./node_modules/node-ssh/lib/cjs/index.js 34:31-46
 @ ./src/api/IBMi.js 4:17-36
 @ ./src/Instance.js 4:13-34
 @ ./src/extension.js 8:15-36

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./node_modules/cpu-features/build/Release/cpufeatures.node 1:0
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/cpu-features/lib/index.js 1:16-60
 @ ./node_modules/ssh2/lib/protocol/constants.js 7:12-35
 @ ./node_modules/ssh2/lib/client.js 33:4-38
 @ ./node_modules/ssh2/lib/index.js 27:10-32
 @ ./node_modules/node-ssh/lib/cjs/index.js 34:31-46
 @ ./src/api/IBMi.js 4:17-36
 @ ./src/Instance.js 4:13-34
 @ ./src/extension.js 8:15-36

webpack 5.24.3 compiled with 1 error and 1 warning in 10033 ms
```

2021-12-04 17:37 UTC, worksofliam commented
@priceaj Do we need to add something to webpack to ignore .node binaries also?

2021-12-04 17:50 UTC, priceaj commented
Do you know what version of node it's running?

2021-12-04 17:53 UTC, worksofliam commented
@priceaj It’s running 14.17.6, which I would have assumed would be ok.

2021-12-04 18:02 UTC, priceaj commented
Yeah should have been, I'll spend some time looking at it tomorrow

2021-12-04 18:02 UTC, worksofliam commented
@priceaj You should be able to open your fork into a Codespace at no cost. Sorry for the trouble.

2021-12-04 18:06 UTC, priceaj commented
Np, if that's what's used by GitHub to do the CI then we will probably get issues. Just a shame there is no configuration in ssh2 which enables you to skip this "optional" dependency without an error!

2021-12-04 18:07 UTC, worksofliam commented
@priceaj Yes.. it’s truly annoying because it’s a great package.

2021-12-06 15:56 UTC, worksofliam commented
@priceaj We may need to run `npm i --no-optional`, though I am not seeing this as a documented argument.

2022-08-14 22:45 UTC, priceaj commented
Closing - I didn't do this in a branch so this has blocked me from making any further changes

2022-08-14 22:45 UTC, closed without merging