Make IFS temporary directory configurable solves #498
halcyon-tech/vscode-ibmi pull request #543
Opened 2022-02-16 14:09 UTC by dferrand

### Changes

Make IFS temporary directory configurable 

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in the README
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2022-02-16 21:10 UTC, worksofliam requested changes
A great PR, but requires some changes.

1. `this.tempPath` should be `this.tempDir` and then is the path to the temporary directory. Code for IBM i then creates files that start with `vscodetemp`
2. We should avoid create path strings and instead use `path.posix.join`. This is partly my fault because I was not doing this before.

Let me know what you think. Thanks!

2022-02-16 21:10 UTC, worksofliam commented on src/api/IBMi.js
> +      let value = `${this.tempPath}-` + Tools.makeid();
I think that instead of 

```
let value = `${this.tempPath}-` + Tools.makeid();
```

We should use

```
let value = path.posix.join(this.tempPath, `vscodetemp-${Tools.makeid()}`);
```

2022-02-16 21:10 UTC, worksofliam commented on src/api/IBMi.js
> +          this.tempPath = `/tmp/vscodetemp`;
As well as this, we should update the user config with the default path when it failed.

```
await config.set(`tempDir`, `/tmp/vscodetemp`)
```

2022-02-16 21:10 UTC, worksofliam commented on src/api/IBMi.js
> +            `rm -f ${this.tempPath}*`
This could be bad since `tempPath` is not a directory. We don't want to delete everything except files we've created.

Could be

```
`rm -f ${path.posix.join(this.tempPath, `vscodetemp*`)}`
```

2022-02-16 21:10 UTC, worksofliam commented on src/api/Configuration.js
> +    this.tempDir = base.tempDir || `/tmp/`;
Remove ending forward slash: `/tmp`

2022-02-16 21:10 UTC, worksofliam commented on src/api/IBMi.js
> +          this.tempPath = this.config.tempDir + `/vscodetemp`;
Remove `/vscodetemp` from this string. Let tempPath be the path to the temporary directory.

2022-02-16 21:55 UTC, dferrand commented on src/api/IBMi.js
> +      let value = `${this.tempPath}-` + Tools.makeid();
done

2022-02-16 21:55 UTC, dferrand commented on src/api/IBMi.js
> +            `rm -f ${this.tempPath}*`
done

2022-02-16 21:55 UTC, dferrand commented on src/api/IBMi.js
> +          this.tempPath = this.config.tempDir + `/vscodetemp`;
done

2022-02-17 04:01 UTC, worksofliam commented
@dferrand Is this ready for me to review again after this latest commit/

2022-02-17 13:56 UTC, dferrand commented on src/api/Configuration.js
> +    this.tempDir = base.tempDir || `/tmp/`;
Done

2022-02-18 18:07 UTC, worksofliam commented
@dferrand Just so you know - this is on my to do list. Got some things going on today, but tomorrow should be the day.

2022-02-18 22:05 UTC, worksofliam commented
@dferrand This is awesome. There are just some last things that need cleaning up.

### Option 1

Since you're not changing `this.tempDir` when the user updates the settings, maybe I recommend you add `tempDir` to the `restartFields` array at `src/webviews/settings/index.js:46`. This means when they change the `tempDir` value, it will ask the user to restart.

### Option 2 (prefered)

In `src/api/IBMi.js`, remove the `this.tempDir` definition and always refer to `this.config.tempDir` - this means when it's updated in the settings, it will reflect right away. Maybe we still want to add `tempDir` to `restartFields` anyway, but it's optional for sure.

Thanks!!

2022-02-18 22:06 UTC, worksofliam commented on src/webviews/settings/index.js
> +        field.description = `User must be authorized to create new files in this directory.`;
Change to

> Directory that will be used to write temporary files too. User must be authorized to create new files in this directory.

2022-02-18 22:07 UTC, worksofliam requested changes
As noted previously.

2022-02-18 23:37 UTC, dferrand commented
I went for option 2.
It's ready for review.

2022-02-18 23:57 UTC, worksofliam commented
@dferrand Perfect - thanks! Looking good. Let's get this merged in.

2022-02-18 23:58 UTC, merged