Add open from IBM i functionality
halcyon-tech/vscode-ibmi pull request #548
Opened 2022-02-19 01:27 UTC by dferrand

### Changes

Add open from IBM i functionnality.

Soves #492

### Checklist

* [x] have tested my change
* [x] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] **for feature PRs**: PR only includes one feature enhancement.

2022-02-19 17:56 UTC, worksofliam requested changes
See changes required.

2022-02-19 17:56 UTC, worksofliam commented on src/api/Configuration.js
> +    this.openFromIbmi = (base.openFromIbmi === true);
New config props also need to be added to the `package.json`.

2022-02-19 17:56 UTC, worksofliam commented on src/api/IBMi.js
> +            `rm -f ${fifo};mkfifo -m 600 ${fifo};/QOpenSys/usr/bin/setccsid 1208 ${fifo}`,
What is `mkfifo`? Does it exist in the system or does it have to be installed? I usually recommend absolute paths for tools like this.

Also, since this is a brand new server dependancy, you will also need to add `mkfifo` to the `remoteApps` at `src/api/IBMi.js:10` to check, then add it to remote features (`IBMi.js:56`) and then you can make this functionality conditional:

```
if (this.config.openFromIbmi && this.remoteFeatures.mkfifo) {
  // Work here
}
```

2022-02-19 17:56 UTC, worksofliam commented on src/api/IBMi.js
> +            readFifo();
I am not sure how I feel about this loop.

Instead of calling `readFifo` within itself, might I suggest you use `setInterval` instead?

Also, it looks like there needs to be some handling if the file hasn't changed. For example, if `readFifo` is called over and over again and the `stdout` is the same path, won't it just keep opening it over and over again? Please correct me if I am wrong here!

2022-02-19 17:56 UTC, worksofliam commented on docs/README.md
> +To open a member or a stream file, simply write its name into a named pipe called `vscodetemp-O__`*`usrprf`* in the temporary IFS directory (/tmp by default).
Perhaps there also need to be some notes that the file content CCSID needs to be ascii/utf8.

2022-02-19 18:47 UTC, dferrand commented on docs/README.md
> +To open a member or a stream file, simply write its name into a named pipe called `vscodetemp-O__`*`usrprf`* in the temporary IFS directory (/tmp by default).
Very good point, I added something. Let me know if it's ok

2022-02-19 18:47 UTC, dferrand commented on src/api/Configuration.js
> +    this.openFromIbmi = (base.openFromIbmi === true);
Forgot to retrofit this one, done.

2022-02-19 18:48 UTC, dferrand commented on src/api/IBMi.js
> +            `rm -f ${fifo};mkfifo -m 600 ${fifo};/QOpenSys/usr/bin/setccsid 1208 ${fifo}`,
mkfifo is a standard unix/posix tool, it creates a named pipe.

It is part of PASE (it can be shadowed by the GNU coreutils one if you have open source tools installed and your path set but it doesn't matter, they both work). It is very similar to cat, rm, etc... I don't feel we should use an absolute path. I also don't see why we would check its existence, PASE would probably be very broken without it.

2022-02-19 18:49 UTC, dferrand commented on src/api/IBMi.js
> +            readFifo();
It is called from an async callback therefore it should not fill the stack.

You can see a named pipe as a blocking unstructured data queue without storage. The read is blocking so cat doesn't return until something has written to the named pipe (and closed it). Also the named pipe doesn't store anything so if a path has been read once, it won't be read again (unless it is written again).

It can be strange if you're not familiar with named pipes, let me know if you have other questions.

2022-02-19 18:50 UTC, dferrand commented
@worksofliam, it's ready for you to review my answers/code changes

2022-02-19 19:09 UTC, worksofliam requested changes
This is awesome @dferrand - I have learned something today.

Please see the last sematic change that is required and I can get this merged. After it's been merged, perhaps we could create a program and put it into the docs which could be called from PDM to write the member path to the file (I can do this).

2022-02-19 19:09 UTC, worksofliam commented on src/api/IBMi.js
> +                await vscode.commands.executeCommand(`code-for-ibmi.openEditable`,result.stdout);
Please add a space between the last comma and `result.stdout`.

E.g. `,result.stdout` becomes `, result.stdout`

2022-02-19 19:12 UTC, worksofliam commented
Much like CL prompting, perhaps we could automatically install this program and set up the PDM option.

From an old PR: https://github.com/halcyon-tech/vscode-ibmi/blob/29a824671b2660d71b1316227eb42f6d19f8e6a9/src/api/JobListener/sources/openmbr.js

2022-02-22 15:41 UTC, dferrand commented on src/api/IBMi.js
> +                await vscode.commands.executeCommand(`code-for-ibmi.openEditable`,result.stdout);
Done

2022-02-22 15:46 UTC, dferrand commented
> Much like CL prompting, perhaps we could automatically install this program and set up the PDM option.
> 
> From an old PR: https://github.com/halcyon-tech/vscode-ibmi/blob/29a824671b2660d71b1316227eb42f6d19f8e6a9/src/api/JobListener/sources/openmbr.js

I added the create of the STRC4I command and program (same way as GENCMDXML).

The automatic creation of the PDM option is a bit problematic since the PDM user defined option file (QGPL/QAUOOPT) is customizable per user profile but there is no official way (AFAIK) to retrieve which file is used by a user (it is stored in the user profile object itself). I opted to explain in the documentation how to create the custom option.

2022-03-02 01:12 UTC, worksofliam commented
@dferrand - this is still on my to-do list. It's a big feature and want to make sure I give it the time it deserves when I review it.

2022-03-07 19:27 UTC, dferrand commented
No worry @worksofliam , take your time.

2022-03-12 21:59 UTC, worksofliam commented
Hi @dferrand - this is looking great! Before I merge this though, I will be looking into another VS Code API which may allow us to use a URL along with `STRPCCMD`. See this comment: https://github.com/halcyon-tech/vscode-ibmi/issues/492#issuecomment-1061111991

2023-01-27 18:11 UTC, closed without merging