Fix system name variant chars
halcyon-tech/vscode-ibmi pull request #714
Opened 2022-06-16 23:56 UTC by chrjorgensen

### Changes

This is quite a big PR so I will try to make a thorough description of the all changes:

#### Motivation

The motivation for creating this PR was the problems in several issues with the variant characters in member names, e.g. issue #701. The problem is complex, and there was still a problem using these characters in the code when I started fixing this: The regexp for validating member names were not correct and had tried to be fixed, but were still not correct. As a non-US user I was also hit by this problem.

#### The problem

The variant characters  '#', '@' and '$' - or rather the hex values 7B, 7C and 5B - are the ones causing the problems. They are allowed in IBM i object and member names - but the representation of these hex values change when the CCSID change! On my system running CCSID 277 (Danish) the variant characters are the special nordic letters 'Æ', 'Ø' and 'Å' (additional letters in our alphabet) instead of '#', '@' and '$'! So it does not work having these characters hardcoded in this extension - because they change according to the setup of the system the user connects to.

#### The solution

My solution was to use SQL to return the local representation of the variant characters - see the change [here](https://github.com/halcyon-tech/vscode-ibmi/blob/348c1a7f6d00af70fe261d1e798f0b1e1f9aee10/src/api/IBMi.js#L490). The output from this is stored in a new IBM i object property called `system_name_variant_chars.local`. The corresponding values from CCSID 37 are store in another new property called `system_name_variant_chars.american`. The two properties are later used for converting names to local or american representation.

#### Parsing member names

Since the properties for the variant characters are part of the IBM i object, I had to move the function `parserMemberPath` from the `Tools.js` source to the `IBMi.js` source - and I had to change all the references to this function. This was probably the biggest change of them all.

#### Difference in retrieving members via SQL and DSPFD

There was another problem: When members are retrieved by using SQL (via QSYS2.SYSPARTITIONSTAT), the file- and member names are returned in CCSID 37 (american), but when retrieved by DSPFD, they are in the locale of the connection! So another change was to have SQL translate the variant characters before returning the values.

#### Sorting the member list

Before my change, the members were sorted by SQL and by DSPFD - and the result were not in the order of my Danish alphabet. I added a sort function to the list of members returned by `getMemberList` - in the locale in VS Code...! I'm not sure this is the best solution, since the order is different from other tools like PDM and RDi. **What do you think about this?**

#### Sorting the object list

After fixing the order of the members I also added a sort to the object list from `getObjectList` - also in the VS Code locale.

#### Searching source files

Finally I fixed searching source files with variant characters in the name.

#### Conclusion

As stated in the beginning, this (to me) is a big change with code changes and source restructuring. I have tested the code to the best of my knowledge, but some errors may have slipped through anyway. So I hope you will give it a thorough look and test and give me some feedback. Let us have this problem fixed once and for all... 💣 

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2022-06-17 23:57 UTC, worksofliam requested changes
What an amazing PR. This is a hardcode problem and you're on point with this PR! Before I do QA and debug, I have some questions and code change requests.

2022-06-17 23:57 UTC, worksofliam commented on src/api/IBMi.js
> +
Before this new block of code, please add a call to `progress report` with a quirky message like "Fetching local encoding values", or whatever you see fit!

2022-06-17 23:57 UTC, worksofliam commented on src/api/IBMi.js
> +              const rows = Tools.db2Parse(output.stdout);
Makes sense, but this this will only ever return one row, I think this should be written like so:

```js
// Fetch first element from result array into row
const [row] = Tools.db2Parse(output.stdout);

if (row && row.LOCAL !== `null`) {
  this.system_name_variant_chars = row.LOCAL;
}
```

This removes the need for a `forEach`.

2022-06-17 23:57 UTC, worksofliam commented on src/api/IBMi.js
> +    const variant_chars_local = this.system_name_variant_chars.local;
Since the initial value of `local` is `undefined`, should we  use `american` as the fallback here? 

```
const variants = this.system_name_variant_chars;
const chars = variants.local || variants.american;
```

2022-06-17 23:57 UTC, worksofliam commented on src/api/IBMi.js
> +    this.system_name_variant_chars = {
I am not sure about the snake case variables. Do we use them elsewhere? I just think it's too long.

I personally think either `variantChars` or `systemChars` would also do the work.

2022-06-17 23:57 UTC, worksofliam commented on src/api/IBMi.js
> +      result = result.replace(new RegExp(`[`+fromChars[i]+`]`, `g`), toChars[i]);
Let's change this to use string interpolation since we mostly use that for other strings throughout the code.

```js
new RegExp(`[${fromChars[i]}]`)
```

2022-06-17 23:57 UTC, worksofliam commented on src/api/IBMi.js
> +      result = result.replace(new RegExp(`[`+fromChars[i]+`]`, `g`), toChars[i]);
Are the square brackets even needed here? I see in `sysNameInAmerican` they are not used?

2022-06-18 13:32 UTC, chrjorgensen commented on src/api/IBMi.js
> +
Progress report has been added in commit [ae7774d](https://github.com/halcyon-tech/vscode-ibmi/pull/714/commits/ae7774d5db73ff9913eb46168fe934791844eab8)

2022-06-18 13:33 UTC, chrjorgensen commented on src/api/IBMi.js
> +              const rows = Tools.db2Parse(output.stdout);
This has now been simplified in commit [ef5ae18](https://github.com/halcyon-tech/vscode-ibmi/pull/714/commits/ef5ae185c31d0fe4ee6adfda23e931ffc2747d4b)

2022-06-18 13:38 UTC, chrjorgensen commented on src/api/IBMi.js
> +    const variant_chars_local = this.system_name_variant_chars.local;
Local chars is set to American chars if no locale characters are found during connection - is that sufficient?

2022-06-18 13:39 UTC, chrjorgensen commented on src/api/IBMi.js
> +    this.system_name_variant_chars = {
I agree the name was too long - I had some difficulty finding a precise name describing the purpose.
It has now been renamed to `variantChars` in commit [60adbc9](https://github.com/halcyon-tech/vscode-ibmi/pull/714/commits/60adbc94b7bc088c84150278d3e74987bfbddbe4)

2022-06-18 13:39 UTC, chrjorgensen commented on src/api/IBMi.js
> +      result = result.replace(new RegExp(`[`+fromChars[i]+`]`, `g`), toChars[i]);
Regexp string has now been changed into string interpolation.

The square brackets are needed - if they are not there, the regexp fails when the char search for is `$`, since this means 'end of text' if not in brackets.

`sysNameInAmerican` does not search for `$`, only replaces with it, so that's why there were no brackets here. However, to make the source similar, I have added them here as well.

See commit [172085b](https://github.com/halcyon-tech/vscode-ibmi/pull/714/commits/172085b3f12536aaab9dc088aebc9050e0febea5)

2022-06-18 13:39 UTC, worksofliam commented on src/api/IBMi.js
> +    const variant_chars_local = this.system_name_variant_chars.local;
Yup! That does make sense!

2022-06-18 13:47 UTC, worksofliam commented
@chrjorgensen thanks for all your changes! I will get some testing done today and let you know how it goes.

2022-06-18 14:33 UTC, chrjorgensen commented
@worksofliam I'm currently testing the change in an environment with QCCSID 65535 (difficult, requires a dedicated LPAR) - and it seems like there are still some problems converting variant chars. Let me work a little bit more on this PR to fix this...

2022-06-18 14:46 UTC, worksofliam commented
@chrjorgensen 65535 will be the death of us. Thanks for letting me know!

2022-06-18 15:02 UTC, chrjorgensen commented
@worksofliam Yeah, I know SQL is disabled when QCCSID is 65535. But even the DSPFD method returns american, when QCCSID is 65535 - even though the user has like 277 (Danish). What should the output be in this case? I would expect Danish characters, not American - what do you think?

2022-06-18 21:34 UTC, chrjorgensen commented
@worksofliam I have now tested connections to systems with different QCCSID values - 037 (US), 277 (DAN) and 280 (ITA). And I have made some new changes to get it all right. Please have a look at these changes.

Btw, did you know that the user CCSID takes priority over the system CCSID? Even though the system value is 65535, there are in fact conversion done if the user has a CCSID other than 65535. So the code is not completely correct, it should test the CCSID on the user before testing the system value. I have also corrected this.

One thing still missing is the member text - in SQL it is returned as UCS2 but in DSPFD it is in CCSID 37...

2022-06-19 00:16 UTC, worksofliam commented
@chrjorgensen That's some serious testing!

> Btw, did you know that the user CCSID takes priority over the system CCSID? 

In what respect? I think the program that runs our SQL does not respect job (user?) CCSID, but does respect the system QCCSID. I could be wrong. I'd have to recheck.. it's been a minute.

I am going to take a look. I wonder what we can actually do about the `DSPFD` returning 37 characters.

2022-06-20 16:10 UTC, worksofliam commented
@chrjorgensen Okay, I've planned some time to take a look at this tonight. Is the only remaining issue member text when coming back as 37 from `DSFPD`?

2022-06-20 21:20 UTC, chrjorgensen commented
@worksofliam Yes, I think the member text when using DSPFD is the only remaining issue (member text using SQL is correct, returned in CCSID 1200).

2022-06-20 21:21 UTC, worksofliam commented
@chrjorgensen do you think I should go ahead and test now? Do you think this is test and merge ready?

2022-06-20 21:28 UTC, chrjorgensen commented
Hi @edmundreinhardt 

Me too - with the variant character problem for decades... 😆 

The combined list of variant characters _could_ be a solution - however, IMHO it may confuse the user when adding source file/member, what characters are allowed - and that the name can be returned differently to the list than specified by the user (because of conversion to CCSID 37 and back to the CCSID of the job).

2022-06-20 21:33 UTC, chrjorgensen commented
@worksofliam Yes, please go ahead 😃

2022-06-21 09:38 UTC, edmundreinhardt commented
> 

I was worried about that too, but we switch to this solution in RDi decades ago (saves dealing with the 65535 nightmare) and not one person of the many customers worldwide has ever complained.
I could get you the list if your were interested.

2022-06-21 12:32 UTC, edmundreinhardt commented
## 		ccsid $ # @ "
##
##############################################################
37 \u0024 \u0023 \u0040 \u0022
256 \u0024 \u0023 \u0040 \u0022
260 \u0024 \u0023 \u0040 \u0022
273 \u0024 \u0023 \u00a7 \u0022
277 \u00c5 \u00c6 \u00d8 \u0022
278 \u00c5 \u00c4 \u00d6 \u0022
280 \u0024 \u00a3 \u00a7 \u0022
281 \u00a5 \u0023 \u0040 \u0022
284 \u0024 \u00d1 \u0040 \u0022
285 \u00a3 \u0023 \u0040 \u0022
290 \u00a5 \u0023 \u0040 \u0022
297 \u0024 \u00a3 \u00e0 \u0022
367 \u005b \u007b \u007c \u007f
420 \u0024 \u0023 \u0040 \u0022
423 \u0024 \u00a3 \u00a7 \u0022
424 \u0024 \u0023 \u0040 \u0022
437 \u005b \u007b \u007c \u001a
500 \u0024 \u0023 \u0040 \u0022
720 \u005b \u007b \u007c \u001a
737 \u005b \u007b \u007c \u001a
775 \u005b \u007b \u007c \u001a
813 \u005b \u007b \u007c \u007f
819 \u005b \u007b \u007c \u007f
833 \u0024 \u0023 \u0040 \u0022
836 \u00a5 \u0023 \u0040 \u0022
838 \u0024 \u0023 \u0040 \u0022
850 \u005b \u007b \u007c \u001a
851 \u005b \u007b \u007c \u001a
852 \u005b \u007b \u007c \u001a
855 \u005b \u007b \u007c \u001a
857 \u005b \u007b \u007c \u001a
858 \u005b \u007b \u007c \u007f
860 \u005b \u007b \u007c \u001a
861 \u005b \u007b \u007c \u001a
862 \u005b \u007b \u007c \u001a
863 \u005b \u007b \u007c \u001a
864 \u005b \u007b \u007c \u001a
865 \u005b \u007b \u007c \u001a
866 \u005b \u007b \u007c \u001a
868 \u005b \u007b \u007c \u007f
869 \u005b \u007b \u007c \u001a
870 \u0024 \u0023 \u0040 \u0022
871 \u0024 \u0023 \u00d0 \u0022
874 \u005b \u007b \u007c \u001a
875 \u0024 \u0023 \u0040 \u0022
878 \u005b \u007b \u007c \u007f
880 \u0024 \u0023 \u0040 \u0022
897 \u005b \u007b \u007c \u007f
905 \u0130 \u00d6 \u015e \u00dc
912 \u005b \u007b \u007c \u007f
914 \u005b \u007b \u007c \u007f
915 \u005b \u007b \u007c \u007f
916 \u005b \u007b \u007c \u007f
918 \u0024 \u0023 \u0040 \u0022
920 \u005b \u007b \u007c \u007f
921 \u005b \u007b \u007c \u007f
922 \u005b \u007b \u007c \u007f
923 \u005b \u007b \u007c \u007f
930 \u00a5 \u0023 \u0040 \u0022
932 \u005b \u007b \u007c \u007f
933 \u0024 \u0023 \u0040 \u0022
935 \u00a5 \u0023 \u0040 \u0022
937 \u0024 \u0023 \u0040 \u0022
939 \u0024 \u0023 \u0040 \u0022
942 \u005b \u007b \u007c \u001a
943 \u005b \u007b \u007c \u007f
948 \u005b \u007b \u007c \u007f
949 \u005b \u007b \u007c \u007f
950 \u005b \u007b \u007c \u007f
964 \u005b \u007b \u007c \u007f
970 \u005b \u007b \u007c \u007f
1025 \u0024 \u0023 \u0040 \u0022
1026 \u0130 \u00d6 \u015e \u00dc
1027 \u0024 \u0023 \u0040 \u0022
1046 \u005b \u007b \u007c \u007f
1089 \u005b \u007b \u007c \u007f
1097 \u0024 \u0023 \u0040 \u0022
1098 \u005b \u007b \u007c \u007f
1112 \u0024 \u0023 \u0040 \u0022
1122 \u00c5 \u00c4 \u00d6 \u0022
1123 \u0024 \u0023 \u0040 \u0022
1124 \u005b \u007b \u007c \u007f
1125 \u005b \u007b \u007c \u001a
1129 \u005b \u007b \u007c \u007f
1130 \u0024 \u0023 \u0040 \u0022
1131 \u005b \u007b \u007c \u001a
1132 \u0024 \u0023 \u0040 \u0022
1140 \u0024 \u0023 \u0040 \u0022
1141 \u0024 \u0023 \u00a7 \u0022
1142 \u00c5 \u00c6 \u00d8 \u0022
1143 \u00c5 \u00c4 \u00d6 \u0022
1144 \u0024 \u00a3 \u00a7 \u0022
1145 \u0024 \u00d1 \u0040 \u0022
1146 \u00a3 \u0023 \u0040 \u0022
1147 \u0024 \u00a3 \u00e0 \u0022
1148 \u0024 \u0023 \u0040 \u0022
1149 \u0024 \u0023 \u00d0 \u0022
1208 \u005b \u007b \u007c \u007f
1250 \u005b \u007b \u007c \u007f
1251 \u005b \u007b \u007c \u007f
1252 \u005b \u007b \u007c \u007f
1253 \u005b \u007b \u007c \u007f
1254 \u005b \u007b \u007c \u007f
1255 \u005b \u007b \u007c \u007f
1256 \u005b \u007b \u007c \u007f
1257 \u005b \u007b \u007c \u007f
1258 \u005b \u007b \u007c \u007f
1275 \u005b \u007b \u007c \u007f
1280 \u005b \u007b \u007c \u007f
1281 \u005b \u007b \u007c \u007f
1282 \u005b \u007b \u007c \u007f
1283 \u005b \u007b \u007c \u007f
1363 \u005b \u007b \u007c \u007f
1364 \u0024 \u0023 \u0040 \u0022
1381 \u005b \u007b \u007c \u007f
1383 \u005b \u007b \u007c \u007f
1386 \u005b \u007b \u007c \u007f
1388 \u00a5 \u0023 \u0040 \u0022
1399 \u0024 \u0023 \u0040 \u0022
4948 \u005b \u007b \u007c \u001a
4951 \u005b \u007b \u007c \u001a
5026 \u00a5 \u0023 \u0040 \u0022
5035 \u0024 \u0023 \u0040 \u0022
5054 \u005b \u007b \u007c \u007f
5123 \u0024 \u0023 \u0040 \u0022
8612 \u0024 \u0023 \u0040 \u0022
9030 \u0024 \u0023 \u0040 \u0022
9066 \u005b \u007b \u007c \u001a
12708 \u0024 \u0023 \u0040 \u0022
25546 \u005b \u007b \u007c \u007f
28709 \u0024 \u0023 \u0040 \u0022
33722 \u005b \u007b \u007c \u007f
62211 \u0024 \u0023 \u0040 \u0022
62224 \u0024 \u0023 \u0040 \u0022
62235 \u0024 \u0023 \u0040 \u0022
62245 \u0024 \u0023 \u0040 \u0022
65535 \u0024 \u0023 \u0040 \u0022

2022-06-21 12:40 UTC, worksofliam commented
@edmundreinhardt this PR will fix this automatically with the use of SQL. This is a very useful list, though!

2022-06-30 19:28 UTC, worksofliam commented
@chrjorgensen sorry this hasn't been reviewed yet. Just having some time off before starting a new job.

2022-06-30 19:44 UTC, chrjorgensen commented
@worksofliam No worry - we all need a break once in a while... 🌤️ Looking forward to hear about your new job!
I also enjoyed the break, it made my mind fresher - and I got some new ideas for improvements! 😆

2022-07-05 23:20 UTC, worksofliam commented
@chrjorgensen good evening! This is the plan: I have to get the next release out for the database changes, then this will be reviewed and merged.

Thanks!

2022-07-08 17:26 UTC, worksofliam commented
@chrjorgensen I went ahead and merged the conflicts from a previous release. Will review now.

2022-07-08 17:53 UTC, worksofliam commented on src/api/IBMi.js
> +            if (this.variantChars.local === undefined) this.variantChars.local = this.variantChars.american;
I think instead of setting `.local` here, the initial value of the variable should be the same as `.american`. I have added a note at the definition too.

2022-07-08 17:53 UTC, worksofliam commented on src/api/IBMi.js
> +      local: undefined
Change `undefined` to be the same as the `american` property.

2022-07-08 17:59 UTC, worksofliam requested changes
@chrjorgensen This is an awesome change and it's working quite well for me. Please see my new comments in the PR code and let's get this merged after this.

> I added a sort function to the list of members returned by getMemberList - in the locale in VS Code...! I'm not sure this is the best solution, since the order is different from other tools like PDM and RDi. What do you think about this?

This is perfectly fine with me. An improvement I think.

> Finally I fixed searching source files with variant characters in the name.

You are going to make a lot of people happy!

2022-07-09 09:28 UTC, chrjorgensen commented on src/api/IBMi.js
> +            if (this.qccsid === undefined || this.qccsid === -2) {
Fixed in commit [403235e](https://github.com/halcyon-tech/vscode-ibmi/pull/714/commits/403235ef09dff94c77a6686870c83788fa01351b)

2022-07-09 09:30 UTC, chrjorgensen commented on src/api/IBMi.js
> +            if (this.variantChars.local === undefined) this.variantChars.local = this.variantChars.american;
Fixed in commit [65d2d03](https://github.com/halcyon-tech/vscode-ibmi/pull/714/commits/65d2d039e989a2c301f77e87fb19c45ca3a03b34)

2022-07-09 09:30 UTC, chrjorgensen commented on src/api/IBMi.js
> +      local: undefined
Fixed in commit [65d2d03](https://github.com/halcyon-tech/vscode-ibmi/pull/714/commits/65d2d039e989a2c301f77e87fb19c45ca3a03b34)

2022-07-09 09:31 UTC, chrjorgensen commented
Hi @worksofliam 
Your requested changes has been added - please re-review now.

2022-07-10 13:16 UTC, merged

2022-07-10 13:56 UTC, worksofliam commented
Thank you @chrjorgensen :)