Make member search respect member type filter
halcyon-tech/vscode-ibmi pull request #767
Opened 2022-07-21 13:23 UTC by chrjorgensen

### Changes

This PR will
- enhance the member search feature to respect any member type filter.
- fix error received when member filter is not ending in `*`.
- fix empty result set when searching in only one member in filter.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2022-07-21 18:16 UTC, chrjorgensen commented on src/api/Search.js
> +      command: `/usr/bin/grep -inHR -F "${term}" ${asp}/QSYS.LIB/${connection.sysNameInAmerican(lib)}.LIB/${connection.sysNameInAmerican(spf)}.FILE/${memberFilter ? connection.sysNameInAmerican(membe
The grep command didn't show the file containing the search term when there were only one file found by the globbing - and I thought it was an error with grep in QSHELL and created a case with IBM. They politely pointed me to the manual for grep, saying it was working as designed... 😆 

And they were right - grep will not show the file if only one file is presented to it on the command line. However, the -H (or --with-filename) option will force it to show it anyway. I had to add the -R to make it work, though. Not very logic, since the [QSHELL grep documentation](https://www.ibm.com/docs/en/i/7.3?topic=data-grep) says the following:

```
-H
    If the -R option is specified, symbolic links on the command line are followed. Symbolic links encountered in the tree traversal are not followed.
. . .
-R
    If file designates a directory, grep searches each file in the entire subtree connected at that point.
```

Not very clear in contrast to the manual for PASE (YUM) grep:

```
H, --with-filename
      Print the file name for each match.  This is the default when there is more than one file to search.
```

So I asked IBM to clarify their documentation...

2022-07-21 18:52 UTC, worksofliam requested changes

2022-07-21 18:52 UTC, worksofliam commented on src/views/objectBrowser.js
> +                      const patternExt = new RegExp(`^` + node.memberTypeFilter.replace(/[*]/g, `.*`).replace(/[$]/g, `\\$`) + `$`);
There is a bug here. Existing filters do not have `memberTypeFilter` and therefore this `replace` is crashing.

```
{
  "collapsibleState": 1,
  "label": "qrpglesrc",
  "filter": "BARRY1",
  "memberFilter": "*",
  "contextValue": "SPF",
  "path": "BARRY1/QRPGLESRC",
  "description": "RPG sourc files",
  "iconPath": {
    "id": "file-directory"
  }
}
```

I think the `if` above could do a simple check to make sure there is a value:

```js
if (results.length > 0 && node.memberTypeFilter) {
  // ...
}
```

2022-07-22 22:35 UTC, worksofliam commented
@chrjorgensen I will test tomorrow and get this merged in ASAP!

2022-07-24 18:39 UTC, worksofliam commented on src/views/objectBrowser.js
> +                      const patternExt = new RegExp(`^` + node.memberTypeFilter.replace(/[*]/g, `.*`).replace(/[$]/g, `\\$`) + `$`);
@chrjorgensen Not sure. I just happened to have a bunch of filters with older filter settings. Something I will think about.

2022-07-24 18:42 UTC, worksofliam commented
@chrjorgensen Retested and looking good! Let's get this merged in. Thank you!!

2022-07-24 18:42 UTC, merged