Add a job browser
halcyon-tech/vscode-ibmi pull request #787
Opened 2022-07-28 17:49 UTC by sebCIL

### Changes

On response at the idea : "[Job browser #304.](https://github.com/halcyon-tech/vscode-ibmi/issues/304)"
That's the first step.

- Add 2 types of liste : My job and all job with subsystem expandable.
- Add the posibilities to a job : 
  - End
  - Change
  - Hold
  - Release
  - Display Joblog

The next step is adding the capability to add a custom filter like Object Browser.

### Checklist

* [X] have tested my change
* [ ] updated relevant documentation
* [X] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2022-07-28 18:12 UTC, worksofliam commented
@sebCIL This is very cool! I need to do a larger review of the code and functionality. That I will do over this weekend. Thanks!

2022-07-29 06:03 UTC, sebCIL commented
I stay tuned if there are improvements to make or bugs to correct.

2022-07-29 13:31 UTC, sebCIL commented
Ok, I made a lot of changes to make it more in line with the initial request.
I hope it will be suitable.

2022-07-29 14:03 UTC, worksofliam commented
@sebCIL great, thanks! I won't be able to review until this weekend or maybe even next week.

@chrjorgensen if you wanted, you're more than welcome to review (also, if I'm bugging you too much then just let me know).

2022-08-01 15:56 UTC, worksofliam requested changes
So first off: this is looking awesome.

Before I continue with my functional tests, I have noted down some places where I would like the command definitions changed. When that is done, I will come back for a second and third review.

Thanks!

2022-08-01 15:56 UTC, worksofliam commented on package.json
> +										"profilFilter": {
`profilFilter` should be `profileFilter`. You're missing the `e` on profile.

2022-08-01 15:56 UTC, worksofliam commented on package.json
> +											"description": "Current user profil",
Same issue with 'profil' here. It is missing the e.

2022-08-01 15:56 UTC, worksofliam commented on package.json
> +								"description": "List of filters for Object List"
Should this be 

> List of filters for Job Browser?

2022-08-01 15:56 UTC, worksofliam commented on package.json
> +				"command": "code-for-ibmi.EndJob",
We use camel case for all our command definitions. Could this be `endJob`?

2022-08-01 15:56 UTC, worksofliam commented on package.json
> +				"command": "code-for-ibmi.ChgJob",
Can this be `changeJob`?

2022-08-01 15:56 UTC, worksofliam commented on package.json
> +				"command": "code-for-ibmi.HldJob",
Can this be `holdJob`?

2022-08-01 15:56 UTC, worksofliam commented on package.json
> +				"command": "code-for-ibmi.RlsJob",
Can this be `releaseJob`?

2022-08-01 15:56 UTC, worksofliam commented on package.json
> +				"command": "code-for-ibmi.HistoryJob",
Also to be `historyJob`.

2022-08-03 16:38 UTC, worksofliam commented
@sebCIL Is this ready for a review again?

2022-08-03 17:07 UTC, sebCIL commented
Okay, I made the requested changes.

2022-08-10 06:08 UTC, sebCIL commented
@worksofliam did you do the review?
Do I need to make any other changes?

2022-08-10 12:13 UTC, worksofliam commented
@sebCIL no review yet, sorry. Been busy with other things, but it will be soon!

2022-08-12 13:44 UTC, worksofliam requested changes
This is really excellent. Thank you for the hard work! Check out the comments I've left, but here's a summary of items that still need to change:

* CSS variables need to used in the history table
* Some grammar and word fixes
* Fix the `create job filter` right click option showing up on all tree items
* Remove command documentation from UI
* We need a page in the documentation for this new view

2022-08-12 13:44 UTC, worksofliam commented on package.json
> +											"description": "Current user profil",
`profil` should be `profile`

2022-08-12 13:44 UTC, worksofliam commented on src/webviews/jobs/filters.js
> +    field = new Field(`input`, `profileFilter`, `Profil`);
`Profil` should be `Profile`

2022-08-12 13:44 UTC, worksofliam commented on src/webviews/jobs/filters.js
> +    field.description = `Specify the name of the subsystem where the job is running.Can be generic name with an asterisk. For example: <code>*</code>, or <code>Q*</code>.`;
There should be a space after `running.` before the first word of the next sentence starts.

2022-08-12 13:44 UTC, worksofliam commented on src/webviews/jobs/index.js
> +            The End Job (ENDJOB) command ends the specified job and any associated inline data files. The job can be on a job queue, it can be active, or it can have already completed running.<br/>
I believe everything between line 25 and 39 should not be part of the web view, but part of the documentation instead.

2022-08-12 13:44 UTC, worksofliam commented on src/webviews/jobs/index.js
> +            The Change Job (CHGJOB) command changes some of the attributes of a job. With the exception of a change in job queue, the job can be in a job queue or in an output queue, or it can be act
This field should not be here. Also part of the documentation.

2022-08-12 13:44 UTC, worksofliam commented on src/webviews/jobs/index.js
> +            The Hold Job (HLDJOB) command makes a job ineligible for processing by the system. The job is held until it is:<br/>
Same here. The command docs don't belong in the web view.

2022-08-12 13:44 UTC, worksofliam commented on src/webviews/jobs/index.js
> +            The Release Job (RLSJOB) command makes a job eligible for processing either after that job is held from processing by the Hold Job (HLDJOB) command, or if the job was submitted to the sys
Same here.

2022-08-12 13:44 UTC, worksofliam commented on package.json
> +				"title": "Holdjob",
This should be `Hold job`

2022-08-12 13:44 UTC, worksofliam commented on package.json
> +					"when": "view == jobBrowser"
I don't think this option needs to show up on every right click option. I think this element can be removed since we can use the navigation button above.

2022-08-12 13:44 UTC, worksofliam commented on src/webviews/history/index.js
> +          border: 0px solid #999999;
We can't hardcode colours in CSS. We have to use CSS variables to respect the chosen user theme: https://code.visualstudio.com/api/extension-guides/webview#theming-webview-content

2022-08-12 13:44 UTC, worksofliam commented on src/webviews/history/index.js
> +          background-color: dimgray;
Same here. Need to use an available CSS variable.

2022-08-15 07:34 UTC, sebCIL commented
@worksofliam Ok, I made the changes.

2022-08-15 07:35 UTC, sebCIL commented on package.json
> +											"description": "Current user profil",
Done

2022-08-15 07:35 UTC, sebCIL commented on src/webviews/jobs/filters.js
> +    field = new Field(`input`, `profileFilter`, `Profil`);
Done

2022-08-15 07:35 UTC, sebCIL commented on src/webviews/jobs/filters.js
> +    field.description = `Specify the name of the subsystem where the job is running.Can be generic name with an asterisk. For example: <code>*</code>, or <code>Q*</code>.`;
Done.

2022-08-15 07:36 UTC, sebCIL commented on src/webviews/jobs/index.js
> +            The End Job (ENDJOB) command ends the specified job and any associated inline data files. The job can be on a job queue, it can be active, or it can have already completed running.<br/>
Remove and creating a documentation

2022-08-15 07:36 UTC, sebCIL commented on src/webviews/jobs/index.js
> +            The Change Job (CHGJOB) command changes some of the attributes of a job. With the exception of a change in job queue, the job can be in a job queue or in an output queue, or it can be act
Remove and creating a documentation

2022-08-15 07:36 UTC, sebCIL commented on src/webviews/jobs/index.js
> +            The Hold Job (HLDJOB) command makes a job ineligible for processing by the system. The job is held until it is:<br/>
Remove and creating a documentation

2022-08-15 07:36 UTC, sebCIL commented on src/webviews/jobs/index.js
> +            The Release Job (RLSJOB) command makes a job eligible for processing either after that job is held from processing by the Hold Job (HLDJOB) command, or if the job was submitted to the sys
Remove and creating a documentation

2022-08-15 07:36 UTC, sebCIL commented on package.json
> +				"title": "Holdjob",
Done.

2022-08-15 07:36 UTC, sebCIL commented on package.json
> +					"when": "view == jobBrowser"
Done.

2022-08-15 07:37 UTC, sebCIL commented on src/webviews/history/index.js
> +          border: 0px solid #999999;
Remove.

2022-08-15 07:37 UTC, sebCIL commented on src/webviews/history/index.js
> +          background-color: dimgray;
Removed.

2022-08-18 15:15 UTC, worksofliam commented
@sebCIL Review will be done this weekend.

2022-08-25 17:19 UTC, worksofliam requested changes
* Code needs to be cleaned up by eslint. Seeing a lot of indentation errors and rule violations regarding strings. This can be done with the eslint VS Code extension.
* Is it possible to add the `JOB_STATUS` to the `ActiveJob` class in the `description` member? This would allow us to see the status in the tree view.
* Long term we plan on creating an 'IBM i Admin'-type view and this will be a good fit for it. That's for much later.

2022-08-26 06:50 UTC, sebCIL commented
I think it was OK.

2022-08-26 14:15 UTC, sebCIL commented
Should I add a condition to load this view only if SQL is enable (in order to protect it from crash)?

Maybe in `Instance.js`, something like that :
```
if (config.enableSQL) {
  context.subscriptions.push(
    vscode.window.registerTreeDataProvider(
      `jobBrowser`,
      new jobBrowser(context)
    )
  );
}
```

Let me know ...

2022-08-26 14:59 UTC, worksofliam commented
@sebCIL Yes, that's a good condition to add!

2022-08-28 06:12 UTC, sebCIL commented
Done.

2022-08-28 16:42 UTC, worksofliam commented
@sebCIL I will get a review done later today, thanks!

The job browser will be the start of something much larger - the 'admin' portion. When I have reviewed and merged, we are going to move the Job Browser into its own panel. The 'IBM i Admin' panel which will be disabled by default, will provide system maintenance type functionality - much like your job browser.

I am trying to draw a clear line between development and admin type work, and moving it into a separate view will help with that.

2022-08-28 16:42 UTC, worksofliam commented
@sebCIL If you wouldn't mind fixing the merge, that would be great.

2022-09-26 20:29 UTC, worksofliam commented
@sebCIL Thought I'd give you an update. I am happy with this PR, but am holding off while I figure out if this belongs in the base of the extension before I go put in the work to put all the 'admin' type functionality (like this PR) into a separate extension.

Thanks!

2022-09-27 06:05 UTC, sebCIL commented
Thank you for the news.
Ok. Let me know if I can help on the 'admin' extension.

2022-11-20 15:14 UTC, worksofliam commented
@sebCIL Ok, there is finally a plan.

The 'admin' extension, which is really just a way to edit objects right now, will be used to host the job browser and eventually the spool file browser.

https://github.com/halcyon-tech/vscode-ibmi-fs

All this work should eventually be ported as a PR over there. That extension is in the early days and we are using a different UI framework, so building the commands you have here will likely work a little different.

2022-11-21 07:28 UTC, sebCIL commented
Thank you for this feedback. 
I'll look into it.

2023-01-13 07:38 UTC, sebCIL commented
@worksofliam I create a PR in the new project. So I close this.

2023-01-13 07:38 UTC, closed without merging