Go to file by entering directly the path (Library / File / Member)
halcyon-tech/vscode-ibmi pull request #833
Opened 2022-08-24 10:07 UTC by sebCIL

### Changes

Description of change here.

### Checklist

* [X] have tested my change
* [ ] updated relevant documentation
* [X] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [ ] **for feature PRs**: PR only includes one feature enhancement.

2022-08-24 13:20 UTC, worksofliam requested changes
This is a great PR. You have basically reimplemented `code-for-ibmi.openFileByPath` by allowing a list and user-input, so here is what I think needs to happen:

* We remove `code-for-ibmi.openFileByPath` completely
* We update the keybinding to `code-for-ibmi.openFileByPath` to point to `code-for-ibmi.goToFile` so the keybinding continue to work.
* The new `quickInput` needs a `prompt` value if it is possible. Something like: 'Select file or enter path' (see the prompt in `openFileByPath`)

Let me know if you can do this. Thank you!

2022-08-24 19:00 UTC, sebCIL commented
Very simple but it works.

Not sure to understand ...

My modifications was in the `code-for-ibmi.goToFile` command not in `code-for-ibmi.openFileByPath`.
I have put a placeholder with  ```quickPick.placeholder = `Go to file..`;``` I can change it to what you want.

2022-08-24 19:06 UTC, worksofliam commented
@sebCIL Since `code-for-ibmi.goToFile` and `code-for-ibmi.openFileByPath` are the same now, I am suggesting we remove `code-for-ibmi.openFileByPath`. 

What do you think of this?

2022-08-24 19:33 UTC, chrjorgensen commented
Is it (still?) possible to open a file in the IFS using this - or is it limited to QSYS filesystem?

2022-08-24 19:45 UTC, worksofliam commented
@chrjorgensen It supports both IFS and QSYS.

2022-08-24 22:37 UTC, chrjorgensen commented
@worksofliam @sebCIL Then we just need to make sure that this is reflected by the prompt or placeholder - that both member and streamfile can be specified.

2022-08-25 06:22 UTC, sebCIL commented
Ok, I made some changes.

2022-08-25 17:36 UTC, worksofliam requested changes
@sebCIL please check like 403 in `Instance.js`. Looks like you've added an additional closing bracket which doesn't need to be there. Then please run eslint for cleanup afterwards.

This is looking great otherwise!

2022-08-25 17:36 UTC, worksofliam commented on src/Instance.js
>          )
Please remove this closing bracket.

2022-08-26 06:54 UTC, sebCIL commented on src/Instance.js
>          )
Oops ....
I remove it and make a eslint review.

2022-08-27 18:34 UTC, worksofliam approved these changes
Tested:

* Opening a member from list
* Opening a streamfile from list
* Opening member from string
* Opening streamfile from string

Great change!

2022-08-27 18:35 UTC, merged