Select from list of previous current libraries
halcyon-tech/vscode-ibmi pull request #844
Opened 2022-08-30 23:19 UTC by chrjorgensen

### Changes

This PR will present the previous current libraries in a list and allow filtering and selection of the libraries in addition to changing current library to library not previously selected:

- Any new value for library name is validated before change.
- Selecting a library from the list will remove the library from the list, push the current library to the list and change the current library to the selected one.
- The final item on the list is `Clear list`.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

2022-08-31 00:33 UTC, worksofliam requested changes
This is a great UX addition. I have requested some changes to the config and validation, but other than that.. love it!

2022-08-31 00:33 UTC, worksofliam commented on src/api/Configuration.js
> +    this.prevCurLibs = base.prevCurLibs || [];
I don't think this config should be saved into the connection settings. I think it is more similar to how we store previously opened files. See `instance.storage.get('sourceList')` as an example and let's use this instead for storing previous current libraries.

2022-08-31 00:33 UTC, worksofliam commented on src/views/libraryListView.js
> +const { list } = require("../../dist/extension");
Guessing this should not be here since we don't want to pull in from `dist` 😄

2022-08-31 00:33 UTC, worksofliam commented on src/views/libraryListView.js
> +                  await connection.remoteCommand(`CHGCURLIB ${newLibrary}`);
I am not sure this is required. We have an internal API in this view `validateLibraryList` which should achieve the same purpose.

```js
const badLibs = await this.validateLibraryList([newLibrary]);
const isBad = badLibs.includes(newLibrary); // went wrong
```

2022-08-31 06:18 UTC, chrjorgensen commented on src/views/libraryListView.js
> +const { list } = require("../../dist/extension");
I don't know how line 6 and 7 ended up being added to this file - it wasn't me! 😭 😆 
Perhaps VS Code auto-added them because of some reference during development?

They will of course be removed!

2022-08-31 06:41 UTC, chrjorgensen commented on src/views/libraryListView.js
> +                  await connection.remoteCommand(`CHGCURLIB ${newLibrary}`);
Yeah, saw that - but the API doesn't return the cause of any problem discovered, i.e. why the library can't be used as current library. So the user won't know what caused the rejection - invalid name, non-existing library, authority, using `QTEMP` as current library, whatever the reason `CHGCURLIB` wouldn't work.

My solution presents the error message from IBM i - although it could be improved by removing the CPFxxxx in the beginning of the error message string.

IMHO some API's for validating libraries, objects and members could provide better feedback to the user - and code. But that is outside this scope...

2022-08-31 06:44 UTC, chrjorgensen commented on src/api/Configuration.js
> +    this.prevCurLibs = base.prevCurLibs || [];
I agree, that was also my first thought - but couldn't make it work. Will try again...

2022-08-31 10:05 UTC, chrjorgensen commented
@worksofliam I have made some changes - please review. 😃 

Note that I have not (yet) changed the `CHGCURLIB` validation to use the `validateLibraryList` API - see my comments above.

To use separators in the QuickPick list, I had to run `npm update` to get the latest `vscode` type definitions. This made some changes to the file `package-lock.json` - should this file be committed?

2022-08-31 15:49 UTC, worksofliam commented
@chrjorgensen 

> To use separators in the QuickPick list, I had to run npm update to get the latest vscode type definitions. This made some changes to the file package-lock.json - should this file be committed?

Yes, do that! We're likely due an upgrade anyway :)

> The redundant code for adding separators to the list - see [cb7da0c](https://github.com/halcyon-tech/vscode-ibmi/pull/844/commits/cb7da0c23d4d78f1e02fb55c0c33349989a361d4).

I see what you're trying to do. We can clean this up later!

Send up the changes to the package files and I'll do a final review!

2022-08-31 16:15 UTC, chrjorgensen commented
@worksofliam Packages updated

2022-08-31 19:59 UTC, worksofliam requested changes
I love it! There is one thing I would like changed.

When I open the input box, I would like the current library as the initial value instead of it being blank.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/3708366/187770879-aebb3f2f-2ed3-404b-8960-3d5a97f26ac4.png">

2022-08-31 20:00 UTC, worksofliam commented
Side note: I love the use of `$(trash)` here!

2022-09-01 10:05 UTC, chrjorgensen commented
@worksofliam How about this:

![billede](https://user-images.githubusercontent.com/13275072/187888204-aed4ad80-3a8c-483f-a295-4292efe025ae.png)

Current library is now presented and selected at the top and pressing Enter will keep the library as current library.
The placeholder text has also been changed to show it is a filter.
I have also restructured the logic for building the quickpick list.

Is it okay?

2022-09-01 11:31 UTC, worksofliam commented
@chrjorgensen that is beautiful! I will check it out today and we'll get it merged.

2022-09-01 21:17 UTC, worksofliam commented
@chrjorgensen Looking great! Thank you for this great PR.

2022-09-01 21:17 UTC, merged