Option to show library description and attribute in User Library List view
halcyon-tech/vscode-ibmi pull request #853
Opened 2022-09-04 21:18 UTC by chrjorgensen

### Changes

This PR will add a configuration value to allow showing library description and attribute in the User Library List view.

This was made optional, since it is quite slow to retrieve the description and attribute for the libraries when SQL is not enabled.

Two techniques were tested during development:

1. retrieving information for one library at a time and
2. retrieving information for all libraries and filter according to the library list

The second option was chosen since there did seem to be any speed difference and this option was easier to code.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

2022-09-04 21:24 UTC, worksofliam commented
Looks interesting... will text over the next few days! Initial reaction is worried about the use of the `SPLIT` function in SQL as not everyone has that (yet)

2022-09-04 21:35 UTC, chrjorgensen commented
> Initial reaction is worried about the use of the `SPLIT` function in SQL as not everyone has that (yet)

Hm, this was built on an IBM i 7.3 system. What is the oldest IBM i release we support? Maybe we should write this in the documentation or README - or I may gotten this info previously but have just forgotten it... 😆 

I can add a check for the `SPLIT` function and if not found, redirect to using the (slower) DSPOBJD method.

2022-09-04 21:37 UTC, worksofliam commented
@chrjorgensen oh yep.. I should read the docs with both eyes. We only support 7.3 and up!

2022-09-04 21:40 UTC, chrjorgensen commented
@worksofliam No need for testing for SQL `SPLIT` function then, i.e. less work for me! 😆

2022-09-04 21:40 UTC, worksofliam commented
@chrjorgensen I am going to get the TS PR merged in first before I get this done. This will be next.

Thank you!

2022-09-04 22:09 UTC, chrjorgensen commented
@worksofliam Just a quick screenshot of what this PR is about...

![billede](https://user-images.githubusercontent.com/13275072/188335311-3971c457-7c00-4917-b170-873f0c0a129a.png)

2022-09-05 14:05 UTC, worksofliam requested changes
Functionally it's looking good. Most of the changes I am requesting is just code-related.

2022-09-05 14:05 UTC, worksofliam commented on src/api/IBMiContent.js
> +   * @param {string[]} libraries
I think a description above `@param` would be useful to describe this method.

2022-09-05 14:05 UTC, worksofliam commented on src/api/IBMiContent.js
> +        const library = libraries[i];
Is this unused?

2022-09-05 14:05 UTC, worksofliam commented on src/views/libraryListView.js
> +        libraries = await content.getLibraryList(new Array(config.currentLibrary).concat(config.libraryList));
Perhaps instead of using `concat`, we could use the spread syntax?

```
[config.currentLibrary, ...config.libraryList]
```

2022-09-05 14:05 UTC, worksofliam commented on src/views/libraryListView.js
> +        libraries = new Array(config.currentLibrary).concat(config.libraryList).map(lib => { return { name: lib, text: ``, attribute: `` }});
Perhaps we could do the same here?

```
[config.currentLibrary, ...config.libraryList].map()
```

2022-09-05 14:11 UTC, chrjorgensen commented on src/api/IBMiContent.js
> +        const library = libraries[i];
No, this is used when showing library text without having SQL enabled...

2022-09-05 14:12 UTC, chrjorgensen commented on src/views/libraryListView.js
> +        libraries = await content.getLibraryList(new Array(config.currentLibrary).concat(config.libraryList));
The slow way...! 😊

2022-09-05 14:19 UTC, chrjorgensen commented on src/api/IBMiContent.js
> +   * @param {string[]} libraries
Fixed in [fe0b4af](https://github.com/halcyon-tech/vscode-ibmi/pull/853/commits/fe0b4afa5147d7658a3f985fc33c7e3f0f39f034)

2022-09-05 14:19 UTC, chrjorgensen commented on src/views/libraryListView.js
> +        libraries = await content.getLibraryList(new Array(config.currentLibrary).concat(config.libraryList));
Fixed in [d5f3d0a](https://github.com/halcyon-tech/vscode-ibmi/pull/853/commits/d5f3d0aedebbac40c5b40d46a7f4595ad82fb55b)

2022-09-05 14:19 UTC, chrjorgensen commented on src/views/libraryListView.js
> +        libraries = new Array(config.currentLibrary).concat(config.libraryList).map(lib => { return { name: lib, text: ``, attribute: `` }});
Fixed in [d5f3d0a](https://github.com/halcyon-tech/vscode-ibmi/pull/853/commits/d5f3d0aedebbac40c5b40d46a7f4595ad82fb55b)

2022-09-05 14:50 UTC, worksofliam commented
Looking good!! I suppose the only downside this is that it has to go and fetch the list again when we move items up/down. Then again, it's not an issue because we can just turn it off. Feature flags are my favourite!

A great PR - thank you @chrjorgensen 

<img width="658" alt="image" src="https://user-images.githubusercontent.com/3708366/188475220-afa9eed2-6bcb-4b89-ac66-4d04c33351fa.png">

<img width="367" alt="image" src="https://user-images.githubusercontent.com/3708366/188475531-779f12a2-f1a5-4261-ba40-2cbb50e9bbde.png">

2022-09-05 14:50 UTC, merged