Add commands to move and sort filters in object browser
halcyon-tech/vscode-ibmi pull request #862
Opened 2022-09-10 18:54 UTC by chrjorgensen

### Changes

This PR will

- add commands to move a filter up and down in the object browser
- add commands to move a filter to top or bottom of the list in the object browser
- add command to sort the filters by name in the object browser

It will solve the request made in issue #861 

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

2022-09-16 13:45 UTC, worksofliam requested changes

2022-09-16 13:45 UTC, worksofliam commented on src/views/objectBrowser.js
> +          console.log(e);
What is the use of the try/catch here? During testing, did something crash for you here?

2022-09-19 09:23 UTC, chrjorgensen commented on src/views/objectBrowser.js
> +          console.log(e);
The code was copied from `sortIFSShortcuts` including the try/catch, I tested without try/catch and no errors were encountered, so the try/catch has been removed.

2022-09-21 16:39 UTC, Wright4i commented
@worksofliam another good PR by @chrjorgensen :)

Tested out fine. Filters move up and down. Saved their position on exit/window reload. Handled up/down/top/bottom gracefully whether the filter was collapsed or not and once reloaded was in the new position with the same state (open or collapsed).

2022-09-21 16:44 UTC, merged