Add command for changing object description
halcyon-tech/vscode-ibmi pull request #863
Opened 2022-09-10 23:15 UTC by chrjorgensen

### Changes

This PR will add a command for changing object description:

![billede](https://user-images.githubusercontent.com/13275072/189504840-cb9a8aeb-e04c-4db3-b7c4-ae7ce8a764c7.png)

![billede](https://user-images.githubusercontent.com/13275072/189504859-4d23a37f-db86-408d-8c62-3355a3fc8ea2.png)

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

2022-09-16 13:43 UTC, worksofliam requested changes

2022-09-16 13:43 UTC, worksofliam commented on src/views/objectBrowser.js
> +            newText = await vscode.window.showInputBox({
Add `validationMessage` to this object.

2022-09-16 13:43 UTC, worksofliam commented on src/views/objectBrowser.js
> +              newTextOK = false;
Instead of doing the length validation here, I think we should use `validationMessage` as noted above in `showInputBox`.

2022-09-16 13:43 UTC, worksofliam commented on src/views/objectBrowser.js
> +                  vscode.window.showInformationMessage(`Changed object description. Reload required.`);
`Reload required` is too vague I think. We use this same phrase when asking users to reload VS Code. Perhaps we could be more specific with something like 'Refresh Object Browser'?

2022-09-19 09:57 UTC, chrjorgensen commented on src/views/objectBrowser.js
> +            newText = await vscode.window.showInputBox({
This has been fixed by commit [444e3c4](https://github.com/halcyon-tech/vscode-ibmi/pull/863/commits/444e3c4896505cf26c86060cc2b7317d23541339)

2022-09-19 09:58 UTC, chrjorgensen commented on src/views/objectBrowser.js
> +              newTextOK = false;
This has been fixed by commit [444e3c4](https://github.com/halcyon-tech/vscode-ibmi/pull/863/commits/444e3c4896505cf26c86060cc2b7317d23541339)

2022-09-19 10:00 UTC, chrjorgensen commented on src/views/objectBrowser.js
> +                  vscode.window.showInformationMessage(`Changed object description. Reload required.`);
The phrase was copied from `code-for-ibmi.renameMember` - but has now been changed to `Refresh object browser` (in both places) by commit [18a80ed](https://github.com/halcyon-tech/vscode-ibmi/pull/863/commits/18a80ed129e29b7491ca937af79921af3e2f1eed)

2022-09-21 16:04 UTC, Wright4i commented
@chrjorgensen does as advertised. Handled almost everything I threw at it. Multiple *BLANKs, hex codes (RI PNK), Changing the description on 5250 while changing in vscode-ibmi.

1 bug I found: backticks.
```
`test`       saves as blank
`test        doesn't save
``test``     saves as test
```

On 5250 doing CHGOBJD backticks are accepted. They do display properly in vscode-ibmi, just can't save them with this PR
![image](https://user-images.githubusercontent.com/93156666/191554239-34ee761f-c160-46e3-b139-4b43cb8917ac.png)

2022-09-21 20:08 UTC, chrjorgensen commented
@worksofliam @Wright4i 

The code has been changed to handle back-ticks in object description. Please try again.

2022-09-21 20:08 UTC, Wright4i commented
@chrjorgensen retested and works. Thanks!

2022-09-21 20:18 UTC, merged