Add option to sort objects by name or type in object browser
halcyon-tech/vscode-ibmi pull request #878
Opened 2022-09-21 22:52 UTC by chrjorgensen

### Changes

This PR will add an option for sorting the objects in object browser by name or type:

![billede](https://user-images.githubusercontent.com/13275072/191624015-14f38386-fe0a-4a9c-9b32-5dd368778615.png)

When this option is enabled, objects are sorted by name and type. If disabled, objects are sorted by type and name - the type being the MI object type, so the list will be sorted like in PDM.

The option is enabled by default to preserve the current behavior of this extension.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [ ] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [ ] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
* [x] **for feature PRs**: PR only includes one feature enhancement.

2022-09-22 01:59 UTC, worksofliam commented on src/api/IBMiContent.js
> +    return new Map([
Is there a reason you are using a map over a key-value object here?

2022-09-22 01:59 UTC, worksofliam commented on src/api/IBMiContent.js
> +      const internalObjType = this.getObjectTypeMap();
Since the result of `getObjectTypeMap` is always the same, maybe we should just make it global somehow?

2022-09-22 11:06 UTC, chrjorgensen commented on src/api/IBMiContent.js
> +    return new Map([
The reason was... my lack of Javascript knowledge and relying on W3Schools... 😆 

But after some investigating on Maps, it seems to me that Maps are more modern than key-value objects - and may perform faster: [https://bretcameron.medium.com/how-javascript-maps-can-make-your-code-faster-90f56bf61d9d](https://bretcameron.medium.com/how-javascript-maps-can-make-your-code-faster-90f56bf61d9d)

Should we keep it?

2022-09-22 11:08 UTC, chrjorgensen commented on src/api/IBMiContent.js
> +      const internalObjType = this.getObjectTypeMap();
Any suggestion on how to make it global and constant? I put it into a separate function at the bottom of the source, since I don't think it should be in the middle of the code.

2022-09-22 14:03 UTC, worksofliam commented on src/api/IBMiContent.js
> +      const internalObjType = this.getObjectTypeMap();
Let me have a think about this and get back to you!

2022-09-22 14:04 UTC, worksofliam commented on src/api/IBMiContent.js
> +    return new Map([
Yes, let's keep it. Thanks!

2022-09-22 14:04 UTC, worksofliam commented
I will look into how where we should put this global object and then we should be good to get going!

2022-10-05 19:16 UTC, worksofliam commented
Will leave update today. Sorry it's been a minute.

2022-10-07 15:06 UTC, worksofliam commented
@chrjorgensen Here is what I think:

See the `schemas` directory. We keep constants and initial values in there. Perhaps the `getObjectTypeMap` method could be extracting into a new ts file and put inside this directory and then brought into `IBMiContent.js`.

What do you think of that?

2022-10-13 08:40 UTC, chrjorgensen commented
@worksofliam I'm sorry, but my TypeScript knowledge is not enough to make a ts import file - so I made a JavaScript import file instead. 😞

2022-10-13 12:06 UTC, worksofliam commented
@chrjorgensen no problem! I will let this in, and then I'm going to do another PR where I convert it to TS. I will let you review that!

2022-10-14 20:10 UTC, worksofliam requested changes
@chrjorgensen Looking good, except one thing! Is the ordering around the wrong way? It looks like it was `Z-A` instead of `A-Z`.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/3708366/195933367-ab0641be-88f3-41c9-868f-a68d7b893fb5.png">

2022-10-14 20:10 UTC, worksofliam commented on src/api/IBMiContent.js
> +          else {
Perhaps the logic here is round the wrong way?

2022-10-14 20:37 UTC, chrjorgensen commented on src/api/IBMiContent.js
> +          else {
No - the sort order shown is by internal(!) object type (the hex value from getObjectTypesMap!

This is the same order as PDM and familiar to IBM i developers. Programs come first, then service programs etc.

2022-10-14 20:41 UTC, worksofliam commented on src/api/IBMiContent.js
> +          else {
Right!! Sorry, I haven't used it in years 😂 

It works great. I am going to try it with a larger library (QSYS) and then will likely merge!

2022-10-14 20:41 UTC, worksofliam approved these changes

2022-10-18 00:36 UTC, merged