Converted Configuration to TypeScript
halcyon-tech/vscode-ibmi pull request #931
Opened 2022-10-30 18:09 UTC by sebjulliand

### Disclaimer
This is my first big PR here, and my take on this conversion may or may not fit the project. I'm all open to discuss it and see it rejected 😊

### Changes
* Converted Configuration to TypeScript
* Used namespaces to differentiate Global configuration from Connections'
* Proposed Configuration interfaces hierarchy
* Added type JSDOC where relevant

### Checklist
* [x] have tested my change
* [x] updated relevant documentation
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)

2022-10-30 18:48 UTC, worksofliam commented
@sebjulliand woah, you weren't kidding!

I will be reviewing this either later tonight or tomorrow morning.

Thanks for your great effort on this front.

2022-10-30 21:45 UTC, sebjulliand commented
Happy to help! I'll be glad to convert more whenever I can.

2022-11-01 14:33 UTC, worksofliam commented
@sebjulliand I fixed a conflict here and now I am going to review.

2022-11-01 14:38 UTC, worksofliam commented on src/api/IBMi.ts
> +      ConnectionConfiguration.update(this.config!);
This is a nice change.

2022-11-01 14:45 UTC, worksofliam requested changes
First off, let me say - this is an amazing PR. I really appreciate the effort of moving some of the most complicated code (the configuration setup is a lot!) into TS.

I very much like the seperation of `GlobalConfiguration` and `ConnectionConfiguration` namespaces.

Other than the two issues I've left comments for, it's all looking good. It just needs some user testing as well.

2022-11-01 14:45 UTC, worksofliam commented on src/webviews/settings/index.js
> +        let {panel, data} = await ui.loadPage(`ConnectionConfiguration: ${name}`);
This should still say `Settings: ${name}` as this is what appears on the tab.

2022-11-01 14:45 UTC, worksofliam commented on src/webviews/settings/index.js
> +          const {panel, data} = await ui.loadPage(`Login ConnectionConfiguration: ${name}`);
This should also still say `Settings`

2022-11-01 14:52 UTC, worksofliam commented
It's working very well for me. Even debugged a little bit to try out the new config APIs.

@halcyon-tech/core Any chance we could do some user testing on this to make sure there is no impact of functionality?

Thanks!

2022-11-01 17:40 UTC, sebjulliand commented on src/webviews/settings/index.js
> +        let {panel, data} = await ui.loadPage(`ConnectionConfiguration: ${name}`);
Eek, that was a **Replace All** that went wrong 😅

2022-11-01 17:40 UTC, sebjulliand commented on src/webviews/settings/index.js
> +          const {panel, data} = await ui.loadPage(`Login ConnectionConfiguration: ${name}`);
Same mistake as above.

2022-11-01 17:46 UTC, sebjulliand commented
> First off, let me say - this is an amazing PR. I really appreciate the effort of moving some of the most complicated code (the configuration setup is a lot!) into TS.
> 
> I very much like the seperation of `GlobalConfiguration` and `ConnectionConfiguration` namespaces.
> 
> Other than the two issues I've left comments for, it's all looking good. It just needs some user testing as well.

Much obliged @worksofliam ! I'm glad to finally have found the time to participate and give back to the community by helping with this great project.

2022-11-01 19:06 UTC, worksofliam approved these changes
Code is good. Further user testing coming.

2022-11-01 19:09 UTC, Wright4i commented
@worksofliam I'll take a look tonight and give my feedback!

2022-11-02 18:01 UTC, worksofliam commented
@Wright4i Any luck with the user testing at all?

2022-11-02 18:20 UTC, Wright4i commented
@worksofliam so far so good! I actually had a bit of work to do this morning on some programs so I've put in a bit of real world testing as well. No issues to report. I'll reach out if something pops up but I think this is good to go.

2022-11-02 18:26 UTC, worksofliam commented
@Wright4i Sorry to pester you, but very glad to hear it's looking good! Will merge this today.

2022-11-02 19:52 UTC, merged