Added Filter to exported types
halcyon-tech/vscode-ibmi pull request #995
Opened 2022-12-21 08:52 UTC by sebjulliand

### Changes
* Extracted and exported `Filter` interface (used by the `fs` extension)
* Added a few types declarations where relevant

### Checklist
* [x] have tested my change
* [x] updated relevant documentation

2022-12-21 19:48 UTC, worksofliam commented
@sebjulliand Looks like we have some conflicts here from the last PR. Can you fix these whenever you have a moment?

Thanks!
Liam

2022-12-23 08:47 UTC, sebjulliand commented
@worksofliam while this PR is still open, I added the error parser to the exported API as well. Hopefully that's OK with you 😉

2022-12-23 14:50 UTC, worksofliam requested changes
Check out my question above. Thanks!

2022-12-23 14:50 UTC, worksofliam commented on src/typings.ts
> +export interface Filter{
I see this interface was added, but I don't see this `Filter` interface used anywhere in this extension.

Is this intentional?

2022-12-23 15:13 UTC, sebjulliand commented on src/typings.ts
> +export interface Filter{
Yes, it's intentional.

I left a comment in the `ObjectBrowser`. I renamed `Filter` class to `FilterItem` and commented that it will implement Filter (it does, but it's implicit at the moment).
Since JS doesn't support implementing an interface, it's all I could do.
This is more or less a `todo` for when I'll convert `ObjectBrowser` to TypeScript 😅

2023-01-12 04:31 UTC, worksofliam commented
LGTM!!

2023-01-12 04:31 UTC, merged